### ISSUE TITLE
Very slowwww performance after plugin enabled

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_routerconfigs#10]
[EDIT] Sorry, I've just read [here](http://forums.cacti.net/viewtopic.php?f=19&t=56823&p=264772&hilit=routerconfigs#p264772) it's still WIP.

I've tried to install and enable this plugin 3 times and every time it is slowing down Cacti's performance.

I've never used this plugin before, don't know how to set it up or what to expect but...this what I've done.

I installed tftp-server and started. I set Misc settings needed (IP and backup directory).

Trying to go from console to graphs or any other page within Console or whatever is taking loong seconds to load.

I don't know where to look to provide more detailed logs,  I could change the log level to debug for a poller cycle and attach it, would that work?
[routerconfigs-debug.txt](https://github.com/Cacti/plugin_routerconfigs/files/756259/routerconfigs-debug.txt)

That's the output from cacti's log after I set to debug that specific plugin.

If I go to "Routers config" there is message "No Router Devices Found"

I previously added a host with Cisco Router template, it's up and graphing.

My current setup

Cacti 1.0.1 from github
Poller CMD.php
PHP 5.3.3
Apache 2.2
MariaDB 10.0.29

Other installed plugins

thold
Monitor
GExport
Webseer (with some "minor" SQL issue)

**Comment by cigamit** [comment]
I'm not too sure what is going, but don't get attached to Webseer, or rather don't invest any time there at the moment.  There is a huge commit coming.  I'm not sure how this is slowing things down, is your Cacti log clear?

**Comment by jpobeda** [comment]
Sorry I mis lead you BUT the issue I'm reporting is with routerconfigs plugin.

the thing with routerconfigs is that to restore the previous performance I have to uninstall it, it doesn't make any different if I just disable it.

Logs are clear, from routerconfigs perspective so I'm not sure what could be causing this issue.

Does this plugin suppose to be working on 1.0.0?

**Comment by cigamit** [comment]
It should work, but we are waiting on a large pull request for a user actively using it.  Could you please define 'slow'?

**Comment by jpobeda** [comment]
Without this plugin installed, I can browse cacti normally from "Console" to "graphs" and takes 0.33 or less  to load it.

Once I install this plugin, same will take 3-4 or more seconds to load pages.

Do you want me to run a trace and attach it?

**Comment by cigamit** [comment]
definitely, use the -tt and -s256 options

**Comment by jpobeda** [comment]
mmm I don't know what's that. I'm not a developer sorry :/

I ran chrome's timeline with "Network" and "JavaScript" ticked.

[TimelineRawData-20170207T144854(without plugin).zip](https://github.com/Cacti/plugin_routerconfigs/files/756356/TimelineRawData-20170207T144854.without.plugin.zip)
[TimelineRawData-20170207T145115 (with routerconfigs).zip](https://github.com/Cacti/plugin_routerconfigs/files/756355/TimelineRawData-20170207T145115.with.routerconfigs.zip)

I could follow your instructions to run it the way it's useful to you.

**Comment by cigamit** [comment]
Looking at the code, your system likely has broken dns.  The only thing that would slow down that page would be a /etc/resolv.conf that is not setup properly.  Which would cause the gethostbyname() function to hang.  I did see an os compatibility error.  So, I'll be making a change there, but that's likely your problem.

**Comment by jpobeda** [comment]
OK...I'll have a look but how come Cacti doesn't complain about it? There are 3 devices added by dns NOT IP and they are working just fine (graphing interfaces by snmpv2 and 3)...and Did I mention that I'm just installing the plugin and NOT enabling it?

I'll have a look but it doesn't look like a dns issue to me It did resolv any name I tried.

**Comment by cigamit** [comment]
I see.  In any case, I can not reproduce it.  Once you have found the root cause, please update this ticket.  For now, there are other things to do and this plugin will be getting a major update pretty soon anyway.

**Comment by jpobeda** [comment]
I won't probably be able to reproduce it again. I upgraded this same installation to 1.0.3 and it works fine.

I haven't change anything on this VM.
