### ISSUE TITLE
When attempting to compare device backups, warning is issued about unsaved changes

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#100]
when you are selecting fields to compare you are prompted with the "Warning Unsaved Form Data" popup at each of the 4 drop down selections. It does not appear that clicking continue or cancel change the result. This Is just annoying having to click continue or cancel 4 times to select a compare.

![screen shot 03-06-19 at 11 31 am](https://user-images.githubusercontent.com/42470924/53974763-53378200-40d1-11e9-990d-4aa40213b1ac.PNG)

**Comment by rtripon** [comment]
Same here.

**Comment by netniV** [comment]
I believe that I applied a fix for this.
