### ISSUE TITLE
Hours do not display properly for retry schedule

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#101]
![Screen Shot 03-14-19 at 03 13 PM](https://user-images.githubusercontent.com/42470924/54385051-11c44b00-466c-11e9-9109-e6caa0d9d6d3.PNG)

**Comment by netniV** [comment]
Which language is this?

**Comment by jdcoats** [comment]
English, looks like 1 hour cut down to our and 2 hours cut down to ours etc

**Comment by netniV** [comment]
This has now been committed to the development code.
