### ISSUE TITLE
Question: how to upgrade from 1.4.0 to 1.5.0

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_routerconfigs#102]
Hey guys,
I noticed that there is a new version of routerconfigs. Can you tell me how to upgrade from 1.4 to 1.5 without loosing all my switches and configuration?

**Comment by netniV** [comment]
If you are worried backup the SQL database (use mysqldump if you like).  The upgrade should just take care of you when you copy over the new version and then visit the plugins management page.

If you have too many issues, you can resolve the plugin_routerconfigs_* tables to revert as long as you copy the previous version of code back too.

**Comment by Axel577** [comment]
That means I should just replace all new files/folders with the current ones?

**Comment by netniV** [comment]
Yes.  Copy away to be safe if you want to rollback at all.

**Comment by netniV** [comment]
@Axel577 If there are no further questions, we can close this?

**Comment by Axel577** [comment]
@netniV one last question: Should I disable the plugin before copying?

**Comment by netniV** [comment]
Better to so that there aren't any polling errors but shouldn't matter too much.
