### ISSUE TITLE
Undefined index connecttype in functions.php

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#103]
```
[20-Mar-2019 00:23:29 America/New_York] PHP Notice:  Undefined index: connecttype in /var/www/localhost/htdocs/cacti/plugins/routerconfigs/include/functions.php on line 448
```
Cacti 1.2.3 dev and Routerconfigs 1.5 dev

**Comment by jdcoats** [comment]
I just noticed that you have made quite a few commits since I last sync'd up. Ill test current :)

**Comment by netniV** [comment]
You may need to set the version of the plugin back to 1.4 if you do.  Just to ensure it runs through the upgrade code again.

**Comment by jdcoats** [comment]
closed
