### ISSUE TITLE
Device types do not populate when installing from scratch

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_routerconfigs#104]
I'm getting the following error when I try to create a device

![image](https://user-images.githubusercontent.com/31240306/54924108-92eccf00-4f03-11e9-9f9b-4266ef1b66c8.png)

another sub-question, in version 1.5 no longer has the types of devices. I have to create them, I do not know if it is a problem here or if the examples have been removed.

I runnig a Cacti 1.2.2 and routerconfigs 1.5.5 on Debian OS

**Comment by netniV** [comment]
They should be there

**Comment by rcsmota** [comment]
I'm not sure why, but after a new installation show this.

![imagem](https://user-images.githubusercontent.com/31240306/54986187-1b25af80-4faa-11e9-8c9f-764fd7c01fd9.png)

On maysql 

![imagem](https://user-images.githubusercontent.com/31240306/54986367-693ab300-4faa-11e9-99a3-515de621749f.png)

**Comment by netniV** [comment]
Where there any errors in the cacti log?

**Comment by rcsmota** [comment]
When I try to create a new device receive error of first post. 
I can create a device type with no problem, but when trying to create a device the error appears in the log and it is not created.

When install the pluguin receive this error too

![imagem](https://user-images.githubusercontent.com/31240306/55000158-d14cc180-4fc9-11e9-9e4d-2e5f19f08671.png)

**Comment by netniV** [comment]
Should be resolved now.

**Comment by rcsmota** [comment]
Hi @netniV 

Now the types are populated but the erro creating host is the same.

![imagem](https://user-images.githubusercontent.com/31240306/55064340-b9307d00-5071-11e9-98a3-f0f7a00fd80d.png)

Should I create a new issue?

**Comment by netniV** [comment]
Too late, I already pushed a change for it.

**Comment by rcsmota** [comment]
You were really fast.  :D

Pluguin updated and now has the types and I can configure a new device. When i try do a backup now has this error.

![imagem](https://user-images.githubusercontent.com/31240306/55085302-59040000-509e-11e9-9d8a-81d0eebb12d8.png)


In debug plugin get configuration via tftp.

![imagem](https://user-images.githubusercontent.com/31240306/55085058-f01c8800-509d-11e9-856e-daee4e21f036.png)

Update: I received a mail with backup was done

![imagem](https://user-images.githubusercontent.com/31240306/55087309-d11ff500-50a1-11e9-9342-69fffe892747.png)

**Comment by netniV** [comment]
Also resolved.

**Comment by rcsmota** [comment]
Hi @netniV 

Same error here.

![image](https://user-images.githubusercontent.com/31240306/55146798-265d1480-513d-11e9-9bde-8159fe206589.png)


I looked to line 78 and devicetype is deviceType now, but the error is the same.

![image](https://user-images.githubusercontent.com/31240306/55146866-412f8900-513d-11e9-8c45-ae541a1bbf7b.png)

**Comment by netniV** [comment]
Yeah spot the spelling mistake 🗡

**Comment by netniV** [comment]
Should be resolved now

**Comment by rcsmota** [comment]
Hi @netniV. It's almost.

Only last lines show up now.

![image](https://user-images.githubusercontent.com/31240306/55162035-d1ca9100-515e-11e9-9009-e95cc5ad0497.png)

I think something is missing on DB. Looking in the table plugin_routerconfigs_backups not have the Field username

![image](https://user-images.githubusercontent.com/31240306/55162341-8a90d000-515f-11e9-8ec8-f9d55bfea6a5.png)

I don't know if should have it or not this field.

**Comment by netniV** [comment]
No, it was renamed to lastuser 👍  Fixed!

**Comment by rcsmota** [comment]
Everything works 100% now.

Many thanks @netniV

**Comment by netniV** [comment]
phew 🏳️
