### ISSUE TITLE
Devices with no devicetype set cause runtime errors

### ISSUE THREAD

**Issue by 1talluglyguy** [Cacti/plugin_routerconfigs#106]
Backup 'Fails' but does appear on tftp server. Interface shows failed backup.
Cacti Logs show:
2019/04/30 09:57:38 - ERROR PHP NOTICE in  Plugin 'routerconfigs': Undefined index: connecttype in file: /var/www/html/cacti-1.2.1/plugins/routerconfigs/include/functions.php  on line: 448
2019/04/30 09:57:38 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/include/functions.php[165]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/include/functions.php[448]:CactiErrorHandler())

I am backing up Cisco routers and switches. I suspect the rotation of old file is the failure.
![image](https://user-images.githubusercontent.com/47432277/56971302-fc7d8000-6b36-11e9-8392-9ed5fe59cfa0.png)
Plugin is 1.5.1
Cacti 1.2.1
Centos 7 
uname -rvp
3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64

**Comment by netniV** [comment]
Do you have the latest development version?  I'm assuming that is 1.5.1 currently.

**Comment by 1talluglyguy** [comment]
Yes I am.

**Comment by netniV** [comment]
```sql
show create table plugin_routerconfigs_devices\G
```

This should result in

```sql
*************************** 1. row ***************************
       Table: plugin_routerconfigs_devices
Create Table: CREATE TABLE `plugin_routerconfigs_devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enabled` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ipaddress` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hostname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `directory` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account` int(11) DEFAULT NULL,
  `lastchange` int(24) DEFAULT NULL,
  `device` int(11) DEFAULT NULL,
  `schedule` int(11) DEFAULT NULL,
  `lasterror` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastbackup` int(18) DEFAULT NULL,
  `nextbackup` int(18) DEFAULT NULL,
  `lastattempt` int(18) DEFAULT NULL,
  `nextattempt` int(18) DEFAULT NULL,
  `devicetype` int(11) DEFAULT NULL,
  `connecttype` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sleep` int(11) DEFAULT NULL,
  `timeout` int(11) DEFAULT NULL,
  `debug` longblob,
  PRIMARY KEY (`id`),
  KEY `enabled` (`enabled`),
  KEY `schedule` (`schedule`),
  KEY `ipaddress` (`ipaddress`),
  KEY `account` (`account`),
  KEY `lastbackup` (`lastbackup`),
  KEY `lastattempt` (`lastattempt`),
  KEY `devicetype` (`devicetype`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Router Config Devices'
1 row in set (0.00 sec)
```

**Comment by 1talluglyguy** [comment]
This is the results…

MariaDB [(none)]> use cacti;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [cacti]> show create table plugin_routerconfigs_devices\G
*************************** 1. row ***************************
       Table: plugin_routerconfigs_devices
Create Table: CREATE TABLE `plugin_routerconfigs_devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enabled` varchar(2) DEFAULT NULL,
  `ipaddress` varchar(128) DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `directory` varchar(255) DEFAULT NULL,
  `account` int(11) DEFAULT NULL,
  `lastchange` int(24) DEFAULT NULL,
  `lastuser` varchar(64) DEFAULT NULL,
  `device` int(11) DEFAULT NULL,
  `schedule` int(11) DEFAULT NULL,
  `lasterror` varchar(255) DEFAULT NULL,
  `lastbackup` int(18) DEFAULT NULL,
  `nextbackup` int(18) DEFAULT NULL,
  `lastattempt` int(18) DEFAULT NULL,
  `nextattempt` int(18) DEFAULT NULL,
  `devicetype` int(11) DEFAULT NULL,
  `connecttype` varchar(10) DEFAULT NULL,
  `sleep` int(11) DEFAULT NULL,
  `timeout` int(11) DEFAULT NULL,
  `debug` longblob,
  PRIMARY KEY (`id`),
  KEY `enabled` (`enabled`),
  KEY `schedule` (`schedule`),
  KEY `ipaddress` (`ipaddress`),
  KEY `account` (`account`),
  KEY `lastbackup` (`lastbackup`),
  KEY `lastattempt` (`lastattempt`),
  KEY `devicetype` (`devicetype`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1 COMMENT='Router Config D  evices'
1 row in set (0.00 sec)

I received the following email:
Summary
0 devices backed up successfully.
1 devices failed to backup.
Devices that failed to backup
Device

Reason

8MSW1

ERROR: SSH no Config uploaded from Router



[cid:image001.png@01D500C7.037181C0]

[cid:image002.png@01D500C7.52244BE0]


Thank you

**Comment by netniV** [comment]
Please download the latest version and it should be sorted now.

**Comment by 1talluglyguy** [comment]
Is there a new version?
[cid:image002.jpg@01D500CC.53FB8AA0]

**Comment by netniV** [comment]
Just download the latest development version.  You won't see a version increase but it should update it.

**Comment by 1talluglyguy** [comment]
What is the latest version?
I have 1.5.1?

Is it someplace other than Gut hub? A dev version????

**Comment by netniV** [comment]
We don’t increment the version all the time on GitHub and I’ve not made a new release.  Just download it again and extract over the top

**Comment by 1talluglyguy** [comment]
I’ve downloaded the latest and deployed the plugin.
I also did a uninstall and reinstalled the plugin. Same result.

The file IS copied tftp to my server though the back up shows failed.

What is the voodoo to get the debug from CLI? Php -q router-download.php ?

**Comment by 1talluglyguy** [comment]
I noticed a little different error with the new version. I included full patches rather than the relative path to the tftp server.
It works now.

Cool tool!!!

Thank you!
