### ISSUE TITLE
New Install of 1.5.1

### ISSUE THREAD

**Issue by micmel5997** [Cacti/plugin_routerconfigs#107]
I am new to using Router Configs and Cacti. I have a new Cacti setup in which I had setup Cacti 1.2.2 and Router Configs 1.5.0. I was having issues adding devices and saw that the issue was fixed in 1.5.1. So I updated Cacti to 1.2.3 and Router Configs to 1.5.1. I then ran into issues and had to install SSH2 for PHP, and got past another error. Where I am at now is that I think SSH is working but am not having any success TFTPing the files to the server. 

I see the below in the logs:

2019/05/03 14:29:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-backups.php[28]:include(), /include/auth.php[28]:require_once(), /include/global.php[466]:include_once(), /include/vendor/csrf/csrf-magic.php[426]:csrf_check(), /include/vendor/csrf/csrf-magic.php[207]:csrf_error_callback(), /include/global.php[462]:CactiErrorHandler())
--
2019/05/03 14:29:03 - ERROR PHP NOTICE: Undefined index: REQUEST_URI in file: /usr/share/cacti/include/global.php on line: 462
2019/05/03 14:28:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-backups.php[28]:include(), /include/auth.php[28]:require_once(), /include/global.php[466]:include_once(), /include/vendor/csrf/csrf-magic.php[426]:csrf_check(), /include/vendor/csrf/csrf-magic.php[207]:csrf_error_callback(), /include/global.php[462]:CactiErrorHandler())
2019/05/03 14:28:57 - ERROR PHP NOTICE: Undefined index: REQUEST_URI in file: /usr/share/cacti/include/global.php on line: 462
2019/05/03 14:27:22 - RCONFIG 172.16.8.1 (SSH) -> ERROR: Failed to find file at /home/configs/backups/Core_Test
2019/05/03 14:27:22 - RCONFIG ERROR: Failed to download 'Core_Test' to '/home/configs/backups/Core_Test' via 'ssh'
2019/05/03 14:23:23 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'title' in 'where clause'

**Comment by micmel5997** [comment]
So I created the folder for the switch name and now I get a new error:

RCONFIG ERROR: Failed to remove pre-existing incoming file: /home/configs/backups/Core

**Comment by netniV** [comment]
That error means the polling user does not have permission to remove that file so we can’t trust a transmit as it may well be the same file rather than an updated one. You’ll need to short the permissions

**Comment by micmel5997** [comment]
I say the folder permissions to 0777?

**Comment by netniV** [comment]
Are you running SELinux?  That will get in the way as well.

**Comment by micmel5997** [comment]
No, SELinux is disabled. :(

**Comment by netniV** [comment]
Is that a file or directory?

**Comment by micmel5997** [comment]
It's a directory.

**Comment by netniV** [comment]
That will be the issue as I think RC expects that the device name is a file containing the config in the TFTP directory

**Comment by micmel5997** [comment]
So when I do a file instead of folder I end up getting the same issue, it appears that TFTP can't create a new file and need to fix that or stop RCONFIG from deleting the existing file.

So I created the file and am able to get it via TFTP locahost and getting the filename. However when I force RCONFIG to get and put the config into this file I get the error. When I try to open that file I notice it is deleted.

**Comment by netniV** [comment]
tftp is the temporary storage location.  The file itself is copied to the backup folder of the plugin.
