### ISSUE TITLE
add router to backup - no way to

### ISSUE THREAD

**Issue by vesparossa** [Cacti/plugin_routerconfigs#11]
Hi support team,
I'm struggling how to add the router/switches to the backup activity since there's no button to me out with this while being on the router tabs under routerconfig section

Cacti version: 1.1.0
Router config: 1.0

![image](https://cloud.githubusercontent.com/assets/7160545/24335405/f3198fbe-127c-11e7-8a2c-9042caca3004.png)

**Comment by cigamit** [comment]
Take the latest version, and then uninstall the plugin and re-install it.  Should have better luck.
