### ISSUE TITLE
Allow confirmation prompt to be dynamically defined

### ISSUE THREAD

**Issue by yagocordoba** [Cacti/plugin_routerconfigs#110]
Hi all

I have a Centos 7.6.1810 with cacti version 1.2.5 and routerconfigs Version 1.5.1
I have installed tftp pointed to /home/configs/backups.
and I want to take the backup from Dell Switch N4064F (Layer 3) this switch works like cisco with the same commands and running-config in the same location when I execute the process manual is copying the backup without problem but when I do it with routerconfigs cacti plugins the debug is showing the follow.

CoreSwitch#copy running-config "tftp://XXXX/SWCORE vrf management"
Transfer Mode.................................. TFTP  
Server IP Address.............................. XXXX
Destination File Path.......................... ./
Destination Filename........................... SWCORE vrf management
Data Type...................................... Config Script   
Source Filename................................ running-config

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) 

**Transfer Canceled!**
CoreSwitch#exit

Attach is the configuration.
¡
![Router Configs Settings](https://user-images.githubusercontent.com/44905003/64028942-a125c380-cb11-11e9-89c2-78ed290c1109.png)
![Router Configs - Device Type](https://user-images.githubusercontent.com/44905003/64029211-2315ec80-cb12-11e9-9af2-0eb9ef4f8bbf.JPG)

Can you help me with the configuration to confirm the backup and it can be executed without issues?

Thank so much!

**Comment by netniV** [comment]
I do not see any log

**Comment by yagocordoba** [comment]
FYI

![image](https://user-images.githubusercontent.com/44905003/64041002-451c6880-cb2c-11e9-8816-4973d0b055c5.png)

**Comment by yagocordoba** [comment]
FYI

![image](https://user-images.githubusercontent.com/44905003/64041438-734e7800-cb2d-11e9-9b4e-087cf8671d70.png)

**Comment by yagocordoba** [comment]
![image](https://user-images.githubusercontent.com/44905003/64045166-a0535880-cb36-11e9-8b99-e612febd9758.png)

**Comment by yagocordoba** [comment]
FYI

![image](https://user-images.githubusercontent.com/44905003/64045367-0fc94800-cb37-11e9-99f6-2e05d1b81a12.png)

**Comment by netniV** [comment]
That suggests your permissions are wrong on that folder.  If you are planning to have your backups under the config user, you'll need to change the paths on the plugin settings and make sure that the poller user has write access to it.

**Comment by yagocordoba** [comment]
Hi!

_I have changed the path on settings - router configs_
![image](https://user-images.githubusercontent.com/44905003/64190519-95edd300-ce44-11e9-8cb3-f4fd8b8af4ca.png)

_also I assigned rights for poller user in that path_
![image](https://user-images.githubusercontent.com/44905003/64192335-78bb0380-ce48-11e9-9996-238956d1095c.png)

_but the error is the same_
![image](https://user-images.githubusercontent.com/44905003/64190854-44921380-ce45-11e9-8f72-47610af9a91c.png)

**_What else could I do to make it work?_**

**_Thanks_**

**Comment by netniV** [comment]
I think the issue here is that you have the TFTP backup path and the Archive as the same path.  They are normally separate paths and are moved from the TFTP to the arfchive.

I would also advise having them separate for security purposes.  That is so you don't have sensitive configurations available via TFTP to anything on the network.

**Comment by yagocordoba** [comment]
Hi! 

I did a modification into the tftp configuration on settings - router config
![image](https://user-images.githubusercontent.com/44905003/64453342-562e2200-d0b6-11e9-86b7-c10b10cd98b9.png)

I create a Device type for Dell devices
![image](https://user-images.githubusercontent.com/44905003/64453352-5d553000-d0b6-11e9-83e4-633c8f6f793d.png)

I configure the Device
 ![image](https://user-images.githubusercontent.com/44905003/64453378-67772e80-d0b6-11e9-90a7-3f9ba0787624.png)

Before executing I Check the status from TFTP server on Centos Server
 ![image](https://user-images.githubusercontent.com/44905003/64453457-955c7300-d0b6-11e9-9bdd-b51ae52e5623.png)

Before test executing the backup manual from switch
 ![image](https://user-images.githubusercontent.com/44905003/64453479-a1e0cb80-d0b6-11e9-8b2b-ffb24317a000.png)

Checking the manual file copied 
 ![image](https://user-images.githubusercontent.com/44905003/64453493-ac9b6080-d0b6-11e9-95c9-67774e8d34ed.png)

Now doing with plugin
 ![image](https://user-images.githubusercontent.com/44905003/64453508-b329d800-d0b6-11e9-8c61-03494bdacc13.png)

Still is not working

**Comment by netniV** [comment]
The reason it failed is given clearly.  The user that the backup process is running under a user that does not have permissions to remove the file/folder that the file was created during your manual run before the process connects and initiates another backup.

**Comment by netniV** [comment]
p.s. sorry for the delay its been a busy time.

**Comment by yagocordoba** [comment]
Hi!
I changed the server configuration and this time I installed my cacti server in a Windows server 2019 and it is running fine, I have installed the Routerconfig pluging to discard error before and I configured the tftpd64 without security parameters and the backups still are not working.
![image](https://user-images.githubusercontent.com/44905003/67017221-6da1f700-f0c7-11e9-824b-b4986bfbd5a6.png)
This is mi currently configuration's pluging
![image](https://user-images.githubusercontent.com/44905003/67017395-b659b000-f0c7-11e9-9783-eca468d48f64.png)
**the version installed is 1.5.1**
This is what is showing the Debug
![image](https://user-images.githubusercontent.com/44905003/67030659-dbf1b400-f0dd-11e9-8cb5-087dc90a9777.png)
This is the error that is showing in the logs 
**RCONFIG ERROR: Failed to connect to Device 'CoreSwitch' using connection type: ssh**
that is weird because if is not getting connection by ssh the debug should not show that it is connected but it is not confirming the backup

ps. When i execute manually directly from ssh shell from Router it is doing the backup withouth issue.

**Comment by netniV** [comment]
OK, so i need sone things, to see the output 

- when it is working manually
- given by routerconfigs (use the debug option on router-download.php)

**Comment by yagocordoba** [comment]
Hi!

thanks for your help I really appreciate!
This is the screenshot when is happening I am executing the backup manually by SSH
![image](https://user-images.githubusercontent.com/44905003/67106906-7c58de80-f199-11e9-9d56-27b61b7552fe.png)
and this is happening when I execute through Router Configs plugin
![image](https://user-images.githubusercontent.com/44905003/67111895-fe4e0500-f1a3-11e9-9692-325ee9b35acc.png)

**Comment by netniV** [comment]
OK, I know what the problem here is.  The code currently is hardcoded to look for "confirm" (in lowercase).  In order to pass, for now, you will have to set FORCE CONFIRM against the device type.

The enhancement will be to add a "Confirmation Prompt" much like we do for one or two other items were the prompt can be different.

**Comment by yagocordoba** [comment]
ok, please let me know when is being release the enhancement because even setting FORCE CONFIRM is happening the same.
![image](https://user-images.githubusercontent.com/44905003/67238364-082d6d80-f41b-11e9-8ccc-64dad691629e.png)

thanks for you help!

**Comment by netniV** [comment]
What model of Dell routers are these?
