### ISSUE TITLE
Enable backup to assume elevation for devices/types that do not offer elevation

### ISSUE THREAD

**Issue by mptcam** [Cacti/plugin_routerconfigs#111]
**Is your feature request related to a problem? Please describe.**
The RourerConfigs is working well with Cisco but not working with HP Comware

**Describe the solution you'd like**
I have a ticket and netniV have ready code to solve this problem, please release this feature

**Comment by netniV** [comment]
This has now been added.  If you were already using the development version, you will need ot set the version to a previous 1.5.0 and then it will update the tables accordingly
