### ISSUE TITLE
Column 'elevated' does not exist, unable to save!

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#112]
I just updated to most recent dev 1.5.1 from a previous dev of 1.5.1 where the column elevated is supposed to be added but evidently setup.php doesn't create the column correctly.

**Comment by netniV** [comment]
Change the version in the plugin_data to 1.5.0 and then update. Because you are updated to the dev version, and were already on 1.5.1 lt doesn’t know to added the field. 

The release will be marked this weekend so anyone coming from 1.5.0 as an upgrade would get it automatically.

**Comment by netniV** [comment]
Oh after changing the version, visits the plugins page again and check it says 1.5.1

**Comment by jdcoats** [comment]
Thanks! That works, I should have realized that without a version change that the updated wouldn't happen. :) You should bump the version when changes to the db are required :)

**Comment by netniV** [comment]
Normally do.  But didn't in this case as we weren't do a full release.
