### ISSUE TITLE
Integration with HP Procurve 

### ISSUE THREAD

**Issue by yagocordoba** [Cacti/plugin_routerconfigs#114]
Hi all

I wanna integrate our HP procurve switch to our current cacti backups system using the plugin RouterConfigs it's working fine with Dell but when I try to do with HP procurve is showing in log section (RCONFIG ERROR: Failed to connect to Device 'Device Name' using connection type: both) 

The current version for Routerconfigs is  1.5.2

Thanks for you help and support

**Comment by netniV** [comment]
How does the ProCurve support downloading it's config?

**Comment by yagocordoba** [comment]
this is the command that I use to do it 
**copy running-config tftp X.X.X.X transfertest.txt**
including the spaces

**Comment by netniV** [comment]
So what can’t router config do that ?

**Comment by yagocordoba** [comment]
when I execute the task is showing the error in logs tab _(RCONFIG ERROR: Failed to connect to Device 'Device Name' using connection type: both)_ I create a new Device type and add follow command to execute the TFTP **copy running-config tftp %SERVER% %FILE%** is ok with that or do I need to change the command?

**Comment by netniV** [comment]
Router Configs uses SSH or Telnet to connect to the remote device, do you have that enabled?

**Comment by yagocordoba** [comment]
Yeah the switch is working with both

**Comment by netniV** [comment]
Then what exactly is the problem? Do you have the full log that you can send to developers@cacti.net?

**Comment by yagocordoba** [comment]
Hi! the email was send on Friday, Feb 14 2020

**Comment by netniV** [comment]
I’ll have to dig through and find it.

**Comment by yagocordoba** [comment]
Hi!
This is the subject
plugin_routerconfigs - issues #114

**Comment by netniV** [comment]
Ah yes, I sent you an email back asking for the debug log with communication enabled so that I can see the input/output of the device.

> Can you enable the debug and connection logging and then send the log for that?  I need to see how the code is interacting with your device.  You should check whether you have any access list restrictions in place to prevent unauthorised access and if so, add the cacti server’s IP to the list. I know that Cisco’s have that feature so I suspect your HP will too.

**Comment by netniV** [comment]
Any update?

**Comment by yagocordoba** [comment]
**HI!
I am trying to figure out where I can find out the debug log I have enable the option on plugin and when I execute still it is showing the same lines in log cacti file**.

2020/03/17 11:42:03 - RCONFIG STATS: Time:0.14 Downloaded:0 Failed:1
2020/03/17 11:42:03 - MAILER INFO: Mail successfully sent via SMTP from 'CACTISVR01 <cati@email.com>', to '@emails', cc '', Subject 'Configuration Backups - Manual: FAILED'
2020/03/17 11:42:03 - RCONFIG ERROR: Failed to connect to Device 'SW Device' using connection type: ssh

![image](https://user-images.githubusercontent.com/44905003/76866347-662f7700-683a-11ea-925e-39fe3baac52a.png)

_Thanks for your help!_

**Comment by netniV** [comment]
The debug log goes against the device in the orange icon:
![image](https://user-images.githubusercontent.com/9052188/78987735-c0b0b000-7b26-11ea-8567-82cf8a162477.png)

**Comment by vKnmnn** [comment]
My Procurves work only with SSH. try setting that as Connection Type and see if it works.

Edit: My bad, you did that already.

**Comment by netniV** [comment]
I take it yours are backing up just fine?

**Comment by vKnmnn** [comment]
yes, they're backing up perfectly

**Comment by yagocordoba** [comment]
Hi! checking the debug it's empty 
![image](https://user-images.githubusercontent.com/44905003/84161426-4379bc80-aa3d-11ea-967b-50ea8bd9527f.png)
and the connection type is in ssh
![image](https://user-images.githubusercontent.com/44905003/84161845-b7b46000-aa3d-11ea-83b3-b6f68389b50f.png)
this is what is showing in the logs
![image](https://user-images.githubusercontent.com/44905003/84162199-1aa5f700-aa3e-11ea-9aba-635938586f31.png)

**Comment by netniV** [comment]
Have you enabled debugging within the routerconfig settings?

**Comment by yagocordoba** [comment]
Yes, it's enabled

![image](https://user-images.githubusercontent.com/44905003/84163739-d1ef3d80-aa3f-11ea-8cd7-1cdec24cf2c4.png)

**Comment by vKnmnn** [comment]
does the switch show a connection attempt in the logs?

**Comment by netniV** [comment]
I'm going to close this due to lack of response.
