### ISSUE TITLE
routerconfigs http 401 trying to access device types

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#120]
I'm not sure at what point this broke but just noticed today that I can no longer access router-devtypes.php
```
[01/Sep/2021:09:13:45 -0400] "GET /cacti/plugins/routerconfigs/router-devtypes.php?tab=devtypes HTTP/1.1" 401 131
[01/Sep/2021:09:13:48 -0400] "GET /cacti/plugins/routerconfigs/router-devtypes.php?tab=devtypes HTTP/1.1" 401 131
[01/Sep/2021:09:13:48 -0400] "GET /cacti/plugins/routerconfigs/router-devtypes.php?tab=devtypes HTTP/1.1" 401 131
[01/Sep/2021:09:13:52 -0400] "GET /cacti/plugins/routerconfigs/router-accounts.php?tab=accounts HTTP/1.1" 200 37540
[01/Sep/2021:09:13:54 -0400] "GET /cacti/plugins/routerconfigs/router-devices.php?tab=devices HTTP/1.1" 200 128304
[01/Sep/2021:09:13:55 -0400] "GET /cacti/plugins/routerconfigs/router-devtypes.php?tab=devtypes HTTP/1.1" 401 131
```
![image](https://user-images.githubusercontent.com/42470924/131683966-9035476a-d960-4c51-8b84-35f65614d6ca.png)

**Comment by netniV** [comment]
Have you checked your permissions against your user ?  This is more a core issue than a router-configs issue.

**Comment by jdcoats** [comment]
Yes, I included the Apache log to show that the other router config pages are available and same result with local cacti admin user. I’m puzzled by it.

Dan
________________________________

**Comment by netniV** [comment]
OK so may be a plugin issue then 👍 I'll take a quick look

**Comment by netniV** [comment]
Can you run the following SQL query:
```sql
select * from plugin_realms where plugin = 'routerconfigs';
```

**Comment by jdcoats** [comment]
I guess that's it then 
```
MariaDB [cacti]> select * from plugin_realms where plugin = 'routerconfigs';
+----+---------------+------------------------------------------------------------------------------+--------------------------+
| id | plugin        | file                                                                         | display                  |
+----+---------------+------------------------------------------------------------------------------+--------------------------+
|  8 | routerconfigs | router-devices.php,router-accounts.php,router-backups.php,router-compare.php | Plugin -> Router Configs |
+----+---------------+------------------------------------------------------------------------------+--------------------------+
1 row in set (0.001 sec)
```

**Comment by netniV** [comment]
OK so that realm appears to be wrong.  Add `,router-devtype.php` to the end of the file column.  I'll see if that's in the setup's upgrade script.

**Comment by TheWitness** [comment]
Was there a bug to be fixed?

**Comment by jdcoats** [comment]
I have no idea, the problem was gone after adding router-devtype.php . It was a year and a half ago.

**Comment by TheWitness** [comment]
Let's let @netniV comment.  I think some of the files were renamed.

**Comment by netniV** [comment]
It seems the plug-in realm didn't get updated to the new list of files. I think that may have been a core issue that was resolved. But I can't be sure.
