### ISSUE TITLE
Can't get Arista to backup

### ISSUE THREAD

**Issue by roscoemcqueen** [Cacti/plugin_routerconfigs#121]
# trying to setup backup of Arista switch. From the CLI via SSH the backup completes correctly as long as the filename already exists. I created an hourly cronjob to create the file if it doesn't already exist. When I try to run the backup via routerconfigs, the exisitng file does move from tftp to my backup folder as expected, but the backup does not complete.

#!/bin/bash
if [ ! -f /srv/tftp/ISCSI_Switch ]
then
   sudo -u tftp -g tftp touch /srv/tftp/ISCSI_Switch
   exit 0
else
   exit 0

fi

from the cli in the switch the command is: copy running-config tftp://192.168.1.68/ISCSCI_Switch
the backup completes without error.

In routerconfigs I have the following options:
![image](https://user-images.githubusercontent.com/91074373/136461218-ff59c483-f40a-4462-a375-15af8a7d2843.png)

I have also tried Assume Elevated - Yes, copy running-config tftp://%SERVER%/%FILE% also without success.

I suspect it's just a text string error, but I cannot figure it out.

**Comment by netniV** [comment]
I will need to see the debug logs of the connection to properly analyse why.  Most devices can be catered for with the current code but we can check if there's something amiss.

Can you email those to developers@cacti.net?

**Comment by roscoemcqueen** [comment]
I worked out the appropriate settings and text string for Arista. Possibly you could add it as an included device type?
The string is copy running-config tftp:%SERVER%/%FILE%

**Comment by netniV** [comment]
If you can send me a dump of the plugin_router_config tables, I can look to include them as a type.

**Comment by roscoemcqueen** [comment]
Here you go
[dump.txt](https://github.com/Cacti/plugin_routerconfigs/files/7331492/dump.txt)
.
