### ISSUE TITLE
Failed to backup switch configuration using the plugin

### ISSUE THREAD

**Issue by azharosman** [Cacti/plugin_routerconfigs#128]
Hi, I am relatively new in Cacti and routerconfigs plugin. I have 2 situations:

When manually run from interface, I got an error 

2023-06-01 17:30:48 - RCONFIG 10.xx.xx.1 (Telnet) -> ERROR: Failed to find file at /var/lib/tftpboot/CoreSwitch
2023-06-01 17:30:48 - RCONFIG ERROR: Failed to download 'CoreSwitch' to '/var/lib/tftpboot/CoreSwitch' via 'telnet'

When run the debug from PHP file, seems fine but no backups

[root@localhost]# php /var/www/html/cacti/plugins/routerconfigs/router-download.php --debug
2023-06-01 17:32:07 - RCONFIG NOTICE: Starting automatic backup
2023-06-01 17:32:07 - RCONFIG WARN: Backup already running since 2023-06-01 17:04:07

Please help me.....

**Comment by netniV** [comment]
Basically, you have your device set to use TFTP to push the configuration from the device to the Cacti server.  If the TFTP isn't setup to use the same folder as the plugin, it won't be able to find the file.  You can also use --force I think to perform a backup even when one is already running.  There is another option, I forget which that shows you communication between the plugin and device to ensure it's responding correctly.  If it isn't, you may need to adjust the prompt settings of the device type you have for this device.

**Comment by azharosman** [comment]
Hi... thanks for the reply. When you said, 

`f the TFTP isn't setup to use the same folder as the plugin, it won't be able to find the file`

Meaning that I shall make the tftp to download inside _/var/www/html/cacti/plugins/routerconfigs_ ?

**Comment by azharosman** [comment]
Hi... updates, I just got it working. It seems that I have to use the 'copy run tftp://xx.xx.xx.xx' to get it done. Thanks for helping!
