### ISSUE TITLE
Does this work with cacti 0.8.8f ?

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_routerconfigs#13]
Hey guys, hey cigamit, 
I have cacti version 0.8.8f and have many cisco IOS switches.
So I decided to try routerconfigs to perform daily backups of the switches.

I'm using routerconfigs 0.3

cacti is installed on an ubuntu 16.04 system and I'm using the tftpd-hpa service.

For testing, I added two cisco switches.

When I manually execute the router-download.php under /usr/share/cacti/site/plugins/routerconfigs/
I always get ERROR: Unknown host

So I thought I try out your version, but when I place the folder into the plugin directory, I get a blank page in Plugin Management in my browser.

So maybe this version doesn't work with cacti 0.8.8f.

Can anybody help me?

**Comment by cigamit** [comment]
All the GitHub plugins only work with the Cacti 1.x.x.  So, your options is to upgrade.  However, you have to be cautious if you have your own plugins that you are dependent upon.  We do not migrate other 3rd party plugins to 1.0.  A good solution is to migtate your production instance to a new system and upgrade/test it.  You can always rsync your rrdfiles when it's all working.
