### ISSUE TITLE
Routerconfig fails to login

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_routerconfigs#15]
Hello, 
I'm trying on new server(cacti 1.1.6) with routerconfig but I cant seem to figure it out why it fails to accept my logins.
��������
    |        |
   |||      |||
.:|||||:..:|||||:.
This is a secured device.
Unauthorized use is prohibited by law.
If you are not authorized to access this device please disconnect.

Username: �� ������'��
% Authentication failed.

Username: 
% Authentication failed.

Username: 
% Authentication failed.

Should I see this caracters or I'm doing something wrong ?.
Error logs in httpd 

[Thu May 25 12:27:19 2017] [error] [client 192.168.0.1] PHP Warning:  strpos(): Empty delimiter in /var/www/html/cacti/plugins/routerconfigs/functions.php on line 828, referer: http://localhost/cacti/plugins/routerconfigs/router-devices.php

[Thu May 25 12:27:38 2017] [error] [client 192.168.0.1] PHP Notice:  fputs(): send of 2 bytes failed with errno=32 Broken pipe in /var/www/html/cacti/plugins/routerconfigs/functions.php on line 854, referer: http://localhost/cacti/plugins/routerconfigs/router-devices.php

**Comment by smiles1969** [comment]
What do you have defined in the username prompt field for the device type selected? Doesn't look like the username is being sent at all. For my Cisco devices, that field value is set to "Username:" and works fine.

**Comment by rtripon** [comment]
Ummm...made some progress following your advice.
Seems the router is now connecting but the expect thingy isnt what it should be.

This is a secured device. 
Unauthorized use is prohibited by law.
If you are not authorized to access this device please disconnect.


Username: �� ������'��test
Password: 

sw#copy running-config tftp://192.168.0.1/
Address or name of remote host [192.168.0.1]? y
Translating "y"

?Invalid host address or name
%Error parsing filename (Invalid IP address or hostname)
sw#

Attached is my device type configuration.
![device types](https://cloud.githubusercontent.com/assets/28921178/26510649/ec883870-4266-11e7-9ca2-62d16b1e7e15.jpg)

I tried with another command : sh run | redirect tftp://192.168.0.1/sw wich works manually (as in the file is copied) but I get some errors after that(prolly the script is expecting something else). Will see if it works automatically.

**Comment by smiles1969** [comment]
Your command only needs to be defined as "copy run tftp".

The address only needs to to be the ip address, or hostname if you are set up to do DNS from your router.

The fact that your 'y' is attempting to perform DNS resolution tells me that it is not.

Also, you can issue "no ip domain lookup" in your router config to keep that annoying lookup attempt from happening if you don't have name servers defined.

Should look like this:

��������

User Access Verification

Username: �� ������'��cacti
Password: 

Example_7606#copy start tftp
Address or name of remote host []? 1.2.3.4
Destination filename [Example_7606-confg]? Example_7606
!!
26550 bytes copied in 0.640 secs (41484 bytes/sec)
Example_7606#

**Comment by rtripon** [comment]
Oh crap..thought it needed the full command. It works, got only one small issue : i didnt input any "enable" password on configuration, but the script is trying anyway.

This is a secured device.
Unauthorized use is prohibited by law.
If you are not authorized to access this device please disconnect.
Username: �� ������'��cacti
Password: 
sw#en
sw#123456
% Unknown command or computer name, or unable to find computer address
test#copy running-config tftp
Address or name of remote host []? 192.168.0.1
!!
15942 bytes copied in 0.934 secs (17069 bytes/sec)
sw#

**Comment by smiles1969** [comment]
That enable part is defined in your "Authentication" tab under the user you have selected for logging into that device. Just clear the enable password field from that user. 

If you have some devices that require enable passwords, and some that don't, just create 2 user accounts with different behaviors and assign them to your devices appropriately.

**Comment by jpobeda** [comment]
@rtripon try the current develop version and close the issue if fixed.

I'm going to give it a go myself since there were lots of commits fixing all those bugs I was also getting.

**Comment by netniV** [comment]
Please make sure you also get the pull requests that are still open until @cigamit  commits them.  There are a couple of 'extra' fixes to my fixes lol

**Comment by jpobeda** [comment]
Yes, I'm actually waiting for it to be merged I feel a bit lazy :O more than usual

**Comment by rtripon** [comment]
Thank you. I'll open a new thread, hopefully with more luck running this plugin :).
