### ISSUE TITLE
HTML Style issue after Enable/Disable devices

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_routerconfigs#16]
I'm setting this up on Cacti 1.1.7 and when I enable or disable a device I get the screen you see attached.

![cacti_routerconfigs_1](https://cloud.githubusercontent.com/assets/13456559/26709832/b4d3e6fc-47a9-11e7-94fa-28439d43feb8.png)

header is set to false.

Also, when I add auth entries, device type, device after I click on 'create' I get a blank page.

![cacti_routerconfigs_ 16_2](https://cloud.githubusercontent.com/assets/13456559/26813876/764b1ce6-4ad5-11e7-9f0f-990de7f9e888.gif)
![cacti_routerconfigs_ 16_3](https://cloud.githubusercontent.com/assets/13456559/26813877/7653e47a-4ad5-11e7-948a-725ab1622266.gif)

**Comment by rtripon** [comment]
Same here.

**Comment by smiles1969** [comment]
Must be some javascript refresh issue, I now have the same problem. However, if I hit F5 and refresh the form before I fill it in and hit save, it works fine.

**Comment by cigamit** [comment]
Resolved.
