### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by africanw** [Cacti/plugin_routerconfigs#17]
Does the plugin still support SSH as most devices have telnet disabled?

**Comment by smiles1969** [comment]
Yes. I have several devices working with SSH.  The plugin will attempt to connect via SSH first, if that fails, it will fall back to telnet.

**Comment by africanw** [comment]
Thanks I tried doing a manual backup from the cacti interface and the logs show this error:

07/19/2017 10:18:13 AM - ROUTERCONFIGS: x.x.x.x-> ERROR: Unable to open telnet network connection
--
2017/07/19 10:18:13 - ERROR PHP WARNING in Plugin 'routerconfigs': fsockopen(): unable to connect to x.x.x.xv:23 (Connection refused) in file: /var/www/html/stats.ecornercloud.com/plugins/routerconfigs/functions.php on line: 854

Version 1.1.12

![device](https://user-images.githubusercontent.com/16145539/28345293-abb821d6-6c6c-11e7-8fdb-2de5daa4e052.PNG)
![device_type](https://user-images.githubusercontent.com/16145539/28345294-aeb601e6-6c6c-11e7-9155-1bb9306d864d.PNG)
![device_auth](https://user-images.githubusercontent.com/16145539/28345297-b16b43d8-6c6c-11e7-8d58-1cfce6300d3d.PNG)

**Comment by Axel577** [comment]
same problem here..
Ubuntu 17.04 with tftpd-hpa; cacti version 1.1.13
Running a tcpdump, routerconfigs doesn't even try ssh. Only telnet.

**Comment by smiles1969** [comment]
A connection refused response is a network connectivity issue, not a plugin code issue. You need to resolve the telnet issue. Have you tried to telnet from the cacti machine to the target host?

Regarding SSH, the code does attempt an SSH connection first before trying telnet, assuming you have properly installed SSH2 support in PHP.

Try this to test:

php -r 'echo (function_exists("ssh2_auth_password") ? "TRUE" : "FALSE");'

**Comment by Axel577** [comment]
smiles1969,
telnet is disabled on all our switches..
Regarding ssh, I installed the SSH2 support in PHP.
The test returns the value "TRUE".

(but I still get the telnet error in the logs.)

**Comment by africanw** [comment]
I was missing the SSH2 module and once in I can see it trying SSH but it cannot log in. I tried auto detect on device type and custom and won't login. Is there a way to see why it's failing?


07/22/2017 02:32:53 PM - ROUTERCONFIGS: x.x.x.x-> ERROR: Unable to open telnet network connection
--
2017/07/22 14:32:53 - ERROR PHP WARNING in Plugin 'routerconfigs': fsockopen(): unable to connect to x.x.x.x:23 (Connection refused) in file: /var/www/html/stats.ecornercloud.com/plugins/routerconfigs/functions.php on line: 854
07/22/2017 02:32:53 PM - ROUTERCONFIGS: x.x.x.x-> ERROR: SSH login failed

**Comment by Axel577** [comment]
ah, you are right! Now my routerconfigs tries ssh, too.

Get the same entries in the log, though:

2017/07/24 10:57:03 - ERROR PHP WARNING in  Plugin 'routerconfigs': ssh2_auth_password(): Authentication failed for  using password in file: /usr/share/cacti/site/plugins/routerconfigs/functions.php  on line: 666
07/24/2017 10:57:03 AM - ROUTERCONFIGS: x.x.x.x-> ERROR: SSH login failed

**Comment by Axel577** [comment]
@africanw Did you get it working?

**Comment by africanw** [comment]
No and not had the time to play with it. If had more debug as to why you could not login could fix it but all it says is cannot login. If I try from the cacti machine I can get in no issues.

**Comment by Axel577** [comment]
I think this is resolved.

**Comment by netniV** [comment]
In reality, there should be an option to say which of these two methods you can use for your device since this generates both unnecessary logs on cacti and the device if it is recording unauthorized access.

**Comment by netniV** [comment]
This can now be resolved as we have moved forward. You can now specify whether to use SSH or Telnet on a per device basis.  The default is to use both, trying SSH first then falling back to Telnet if we have to.

**Comment by netniV** [comment]
@Axel577 can we close this one now?

**Comment by Axel577** [comment]
Sure, but I can't do this, it's not my thread.

**Comment by netniV** [comment]
Fair enough, @africanw can we close this?

**Comment by Axel577** [comment]
I meant, I can't technically close it, can I ?

**Comment by netniV** [comment]
No, hence I asked @africanw  👍

**Comment by Axel577** [comment]
I don't think you get an answer, can't you close it?

**Comment by netniV** [comment]
Not yet.  I'm just a contributor like anyone else.

**Comment by africanw** [comment]
Sure.

Regards,
Grant Longhurst
Infrastructure Manager
eCorner Pty Ltd

Phone: +61 2 9494 0200
Email: grant.longhurst@ecorner.com.au<mailto:grant.longhurst@ecorner.com.au>

Web - www.ecorner.com.au
Buy a store - www.ecorner.com.au
Need Support -  support@ecorner.com.au<mailto:support@ecorner.com.au>

**Comment by netniV** [comment]
@africanw or @cigamit please close this then 👍
