### ISSUE TITLE
Update 0.3 to 1.1

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_routerconfigs#18]
Hi, I'm using a routerconfigs  ver 0.3 on a Cacti 0.8.8a. Who can I update the routerconfig to version 1.1? 

I try replace the folder on cacti's plugins folder but I lost access to Plugin Management. 

Thanks.

**Comment by cigamit** [comment]
Once you update to the latest Cacti, you will be able to install the plugins from GitHub.  None of them are supported on the older Cacti.
