### ISSUE TITLE
Routerconfig Error -> Disabled

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#19]
Im using a fresh installed cacti 1.1.17 with a today downloaded routerconfig from github on debian stretch.

When i click on the "compare" button routerconfigs gets disabled and the following error is logged to cacti.log:

2017/09/05 13:54:47 - ERROR PHP PARSE in  Plugin 'routerconfigs': syntax error, unexpected 'new' (T_NEW) in file: /var/www/cacti/plugins/routerconfigs/Text/Diff.php on line: 330
2017/09/05 13:54:47 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4459 cacti_debug_backtrace)
2017/09/05 13:54:47 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'

Maybe its just because everything is empty.

**Comment by jpobeda** [comment]
So can you actually backup devices or you're just clicking the compare button to see what happens?

**Comment by seppeel** [comment]
Was just to see what happens, there are now devices to backup right now.
Its just very irritating and first thought i cannot use the plugin at all.
So...no high priority here :-)

**Comment by cigamit** [comment]
I suspect it's your PHP version.  Can you please indicate it here?

**Comment by seppeel** [comment]
Its PHP 7.0.19-1
Its the default package for Debian Stretch.

**Comment by cigamit** [comment]
Could be.  Run this, post the results:

`cd /var/www/html/cacti/plugins/routerconfigs`
`find . -name \*.php -exec php -l {} \;`

If anything comes back with a syntax error, see if you can resolve it.  Then, create a pull request with the changes.

**Comment by seppeel** [comment]
I now installed cacti + routerconfigs on ubuntu 16.04 with php 7.0.22
 -> Same error.

```
cd /var/www/html/cacti/plugins/routerconfigs
find . -name \*.php -exec php -l {} \;
```

finds the following errors:

```
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff.php on line 330
Errors parsing ./Text/Diff.php
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff/Renderer.php on line 100
Errors parsing ./Text/Diff/Renderer.php
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff/Engine/native.php on line 108
Errors parsing ./Text/Diff/Engine/native.php
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff/Engine/xdiff.php on line 47
Errors parsing ./Text/Diff/Engine/xdiff.php
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff/Engine/string.php on line 88
Errors parsing ./Text/Diff/Engine/string.php
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./Text/Diff/Renderer/table.php on line 172
Errors parsing ./Text/Diff/Renderer/table.php
```

I will create a PR.

**Comment by cigamit** [comment]
That's very odd.  Travis has it syntax checking appropriately.  There is an updated Horde library out on GitHub, I was reluctant to simply upgrade it since I can not test it.  Maybe, if I commit it, you can test it?  Is for the visual compare stuff.

**Comment by seppeel** [comment]
Ah, i just saw you were already on it. i can test whenever i have time to do that (im at work and i can only test here at work)

**Comment by cigamit** [comment]
Okay, I'm going to update to the latest horde library.  Let me know how the test goes.  It's all staged.  Be in shortly.

**Comment by seppeel** [comment]
Seems like this Issue can be "reolved". I dont have any errors using the compare function.
The problem is, that i cannot test really the compare function, because i have more issues getting backups.

I will open a separate issue for that.

**Comment by cigamit** [comment]
I'll close this then.  I did a bunch of merges to get the TextDiff class up-to-date.
