### ISSUE TITLE
IOS-XR Device Type

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_routerconfigs#2]
I have defined a device type for Cisco IOS-XR routers, but am unable to get the plugin to recognize a telnet connection to this device type. The username prompt is the same as IOS, and the database records look identical, but I figured I would separate them for troubleshooting purposes. 

Any suggestions?

**Comment by smiles1969** [comment]
From what I can determine from the debug console, the initial response for IOS-XR looks different, I.E the control characters are different. I am assuming the telnet session is not handshaking correctly.

**Comment by cigamit** [comment]
Can you please respond with the telnet responses so that we can alter the script to handle this?

**Comment by smiles1969** [comment]
This is a working IOS debug console output:

��������
User Access Verification

Username: �� ������'��cacti
Password: 

hostname#copy start tftp

**Comment by smiles1969** [comment]
Here is an IOS-XR console output:

���� ��#��'��$��!���������� ����'�����������

**Comment by smiles1969** [comment]
do you need a pcap file, I can capture the traffic with tcpdump...

Or any other way to capture this via logs or additional debugging options?

**Comment by smiles1969** [comment]
[ios-xr.zip](https://github.com/Cacti/plugin_routerconfigs/files/694314/ios-xr.zip)

Attached is a pcap of an attempted telnet session to IOS-XR device (Cisco ASR9000)

**Comment by smiles1969** [comment]
Cisco Debug logs as well:

RP/0/RSP0/CPU0:ASR9K#RP/0/RSP0/CPU0:Jan 18 12:33:24.536 central: TELNETD_[65898]: Starting TELNETD EVENTS
RP/0/RSP0/CPU0:Jan 18 12:33:24.546 central: TELNETD_[65898]: Sent : IAC DO TERMINAL TYPE
RP/0/RSP0/CPU0:Jan 18 12:33:24.547 central: TELNETD_[65898]: Sent : IAC DO TSPEED
RP/0/RSP0/CPU0:Jan 18 12:33:24.547 central: TELNETD_[65898]: Sent : IAC DO XDISPLOC
RP/0/RSP0/CPU0:Jan 18 12:33:24.547 central: TELNETD_[65898]: Sent : IAC DO NEW-ENVIRON
RP/0/RSP0/CPU0:Jan 18 12:33:24.547 central: TELNETD_[65898]: Sent : IAC DO OLD-ENVIRON
RP/0/RSP0/CPU0:Jan 18 12:33:24.547 central: TELNETD_[65898]: Sent : IAC DO LFLOW
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WILL  NAWS
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Sent : IAC DO NAWS
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WILL  TSPEED
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WILL  TERMINAL TYPE
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WILL  NEW-ENVIRON
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC DO ECHO
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Sent : IAC WILL ECHO
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WILL  SUPPRESS GO AHEAD
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Sent : IAC DO SUPPRESS GO AHEAD
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC DO SUPPRESS GO AHEAD
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Sent : IAC WILL SUPPRESS GO AHEAD
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WONT  XDISPLOC
RP/0/RSP0/CPU0:Jan 18 12:33:24.548 central: TELNETD_[65898]: Received : IAC WONT  OLD-ENVIRON
RP/0/RSP0/CPU0:Jan 18 12:33:24.551 central: TELNETD_[65898]: Received : IAC WONT  ECHO
RP/0/RSP0/CPU0:Jan 18 12:33:24.551 central: TELNETD_[65898]: Received : IAC WONT  LINEMODE
RP/0/RSP0/CPU0:Jan 18 12:33:24.551 central: TELNETD_[65898]: Received : IAC DONT STATUS
RP/0/RSP0/CPU0:Jan 18 12:33:24.551 central: TELNETD_[65898]: Received : IAC WONT  LFLOW
RP/0/RSP0/CPU0:Jan 18 12:33:24.641 central: TELNETD_[65898]: Sent : IAC DO ECHO
RP/0/RSP0/CPU0:Jan 18 12:33:24.641 central: TELNETD_[65898]: Sent : IAC WILL STATUS
RP/0/RSP0/CPU0:Jan 18 12:33:24.641 central: TELNETD_[65898]: Sent : IAC DO LFLOW

**Comment by smiles1969** [comment]
I got IOS-XR devices working with SSH, but they still will not handshake on telnet.

**Comment by netniV** [comment]
@smiles1969 RouterConfigs has been updated to have a more concise and common base code for Telnet and SSH.  Can you try this version and let me know if it works for you?

Failing a response, we will go ahead an close this.

**Comment by cigamit** [comment]
No response.
