### ISSUE TITLE
Error trying to backup

### ISSUE THREAD

**Issue by raikone14** [Cacti/plugin_routerconfigs#20]
Hi fellas, 
I trying to do a banckup  but is returning this errors:

10/04/2017 01:00:18 PM - ROUTERCONFIGS: 10.5.1.100-> WARNING: Unable to open ssh network connection
--
2017/10/04 13:00:18 ```
- CMDPHP PHP ERROR WARNING Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 189 Connect)(/plugins/routerconfigs/functions.php: 662 ssh2_connect)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)
2017/10/04 13:00:18 - ERROR PHP WARNING in Plugin 'routerconfigs': ssh2_connect(): Unable to connect to 10.5.1.100 in file: /opt/cacti/plugins/routerconfigs/functions.php on line: 662
2017/10/04 13:00:18 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 189 Connect)(/plugins/routerconfigs/functions.php: 662 ssh2_connect)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)
2017/10/04 13:00:18 - ERROR PHP WARNING in Plugin 'routerconfigs': ssh2_connect(): Unable to connect to 10.5.1.100 on port 22 in file: /opt/cacti/plugins/routerconfigs/functions.php on line: 662
2017/10/04 13:00:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 189 Connect)(/plugins/routerconfigs/functions.php: 636 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2017/10/04 13:00:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Array to string conversion in file: /opt/cacti/plugins/routerconfigs/functions.php on line: 636

```
Any idea how to solve ? thank you guys...

**Comment by smiles1969** [comment]
Are you trying to SSH or Telnet to this device? Have you verified you can connect to this device from your Cacti server via CLI?

You can comment out or remove that line 636 in functions.php, it is for troubleshooting only, but there is nothing helpful in these logs other than it's saying you have a network connectivity issue using SSH to connect to the far end device.

If SSH fails, it should be attempting telnet immediately after, and those logs are not included in this post.

**Comment by rcsmota** [comment]
Hello.

I have the same problem and my cisco device can be accesed via telnet or SSH.

This is my output:

12/05/2017 06:59:05 PM - ROUTERCONFIGS: 192.168.50.2-> ERROR: SSH login failed
2017/12/05 18:59:05 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/routerconfigs/router-devices.php: 135  actions_devices)(/plugins/routerconfigs/router-devices.php: 305  plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php:  189 Connect)(/plugins/routerconfigs/functions.php: 666  ssh2_auth_password)(CactiErrorHandler)(/lib/functions.php: 4403  cacti_debug_backtrace)
2017/12/05 18:59:05 - ERROR PHP WARNING in  Plugin 'routerconfigs':  ssh2_auth_password(): Authentication failed for  using password in file:  /opt/cacti/plugins/routerconfigs/functions.php  on line: 666
2017/12/05 18:59:05 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-devices.php: 135  actions_devices)(/plugins/routerconfigs/router-devices.php: 305  plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php:  189 Connect)(/plugins/routerconfigs/functions.php: 636  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/12/05 18:59:05 - ERROR PHP NOTICE in  Plugin 'routerconfigs':  Array to string conversion in file:  /opt/cacti/plugins/routerconfigs/functions.php  on line: 636

![image](https://user-images.githubusercontent.com/31240306/33622414-ab338b6a-d9e5-11e7-8a3c-efe169f2f001.png)

Thanks.

**Comment by netniV** [comment]
RouterConfigs has now been updated. There is one more outstanidng pull request to be integrated.  But I believe this issue should now be resolved.  If so, please close this.

**Comment by cigamit** [comment]
No response.
