### ISSUE TITLE
Improve Backup Directory Structure

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/plugin_routerconfigs#27]
When adding or editing a device, the directory validation always fails unless the full path is added, however this would still be incorrect as the path added in configuration > settings > misc > backup directory path would be prepended.

Also, 
setting backup directory path as "/" or blank results in an error message when attempting a backup.

Example 1
backup directory path set to /tftp
Device Directory set to localrouters
Validation fails, but backup is successful. 
File is saved as: /tftp/localrouters/hostname-date-time
Backups tab shows directory as "localrouters"

Example 2
backup directory path is set to /tftp
Device directory is set to /tftp/localrouters
Validation succeeds, backup is successful
File is saved as: /tftp/tftp/localrouters/hostname-date-time
Backups tab shows directory as "/tftp/localrouters"

**Comment by netniV** [comment]
Yeah I spotted that one too.  Also, the relative directory needs to be NOT a device name because that causes problems with TFTP too.  In truth, I'm not sure it should be hard coded to be under the TFTP directory as really, do you want all the configurations available via TFTP so easily??

**Comment by chris-technicate** [comment]
Now that cacti has introduced sites, that may solve the problem of dumping 100 devices in the same directory.

My suggestions:
1) Settings > Misc > Option to "Organize by site"
2) Router Configs > Device Settings > Use Default Directory (pulls from settings > misc, AND greys out directory)
3) Router Configs > Directory > Complete path overrides settings if "Default Directory" not checked. (must be complete path, use same validation)

**Comment by netniV** [comment]
Whilst Cacti has sites, aren't routerconfigs' devices separate too that? Or are you proposing that we pull in the site data but link it to routerconfigs too?

**Comment by chris-technicate** [comment]
Long long ago, mere months after the plugin was originally released, I had proposed integrating router configs as an option to devices similar to thresholds. I.e. Device Template > Add "Backup Template" Backup Template being the "Device Types" Template.

In my head it does not make sense you would be backing up an item you are not already graphing / monitoring, but I could be wrong.

Either way, it was only a suggestion. If that creates a rabbit hole then avoid it for now. Stability of the plugin in the 1.X branch is far more important than convenience features.

**Comment by netniV** [comment]
But I so like the rabbit holes you send me down @chris-technicate  👍 🤣 🔫

**Comment by chris-technicate** [comment]
to be fair @netniv I just point out a bug - Many times if I knew the depth of said hole I **may** have kept my mouth shut.

Like me, you see a problem, and it must be fixed. Much respect!!

**Comment by andersonreloaded** [comment]
Hi Folks,

For the pre 1.x.x Cacti versions, we have written custom script in Perl and later ported it to PHP.
The filename for the backup is provided by the script, instead of leaving it to default value. If the directory name for backup is same as the device name, then the first backup is a success and all subsequent backups fail with "Failed to remove pre-existing incoming file".

Subsequently, we developed SNMP based scripts to do configuration backup instead of Telnet/SSH.
This required enabling SNMP RW access and needs careful access control policies.

Can we discuss ideas on these line to improve the plugin.
Cheers!

**Comment by netniV** [comment]
I've just sent you an email, if you send me over the script, I'll see how that translates to the plugin.  However, that should really be on an issue of it's own to be investigated.

**Comment by jpobeda** [comment]
I think the plugin should take total control of Directory paths and file creations. 

Makes it easier to troubleshoot and the user to understand how to set it up.

Let's say something like

When you define "Directory directive" you could select "individual or generic" so Individual would take hostname as base name to create the directory and / for the generic.

Why not just create an activity, let's say, "Daily", "Weekly", etc. with the date/time and directory settings and group devices meeting the same criteria also?

I know all this involves rework, just suggesting. At the end, I'm not sure you get much of a benefit from storing files into individual directories. I think the plugin could sort that out for the user instead by strictly using name conventions and having full control over the names and directories to create.

**Comment by netniV** [comment]
I have always stored configurations for different devices in different directories as I have configurations going back years.  The main reason for that being that. for example, I am often told that something worked months/years ago for one client but now they need it back for another.

I appreciate and agree that if you decide to only have a history of two files per device and four devices.  It seems to be counter-intuitive to actually put all those in different directories.  Once scaled up, you'll probably want to do that but I wouldn't be making that RouterConfigs responsibility.

**Comment by chris-technicate** [comment]
I have to agree here with netniV.

Take it from someone backing up over 100 devices daily in 8 different locations. Folder for location, folder for device, all backups for a device in that folder.

You solution while elegant does not scale.

**Comment by jpobeda** [comment]
What doesn't scale is routerconfig plugin...

100 devices isn't big deal.. from what I've just tested I wouldn't use this in a prod environment for more than 20-30 devices. The management interface doesn't scale.

I guess what I was trying to say is, directory structure should be fully customizable if you want BUT the plugin should take absolute control over it, offer a browsing directory option, validate and create/delete the structure. Correct me if I'm wrong, but nowadays the user has to create the directories. With a good mgmt interface you should search for the device date/time backup and get it from there without caring about dir structure. Ambitious, I know.

To be honest I have kiwi cattools and that's the reason I'm giving this a go but is way behind the basic functions of kiwi cattools and it's very affordable.

Don't get me wrong! keep up the good work.

**Comment by netniV** [comment]
You are saying that 100 devices isn't a big deal.  For one device over the last year, I have ~250 - 300 configurations.  Multiple that up by a factor of 100, that's a minimum of 2,500 files.   That is a lot of files to handle in a single directory from a human point of view and yes, sometimes I like to get down and dirty with my configuration files.  Like I said, I can appreciate that people with a small number of devices who rarely change a configuration would probably want things in a single directory.

I'm curious how you say that the management interface doesn't scale?  It may not based off the settings you are using but I'm pretty sure that we have added filtering, paging and searching onto the devices and backup tabs to make sure that things can scale on the front end.  I have certainly had no speed issues.

**Comment by netniV** [comment]
Whilst I remember, @andersonreloaded, did you send me an email with the script in?

**Comment by jpobeda** [comment]
@netniV I didn't explain that very well on my first comment but my last comment was clear enough.

I'm dropping the discussion here because I'm not adding any value to it and having tried the plugin I'm no longer interested.

I apologize if I have offended any of you with any of my comments.

**Comment by netniV** [comment]
You haven't.  I'm just curious because if there's room for improvement on the interface, it's worth looking at.  There wasn't much added in the comment before your last one other than you're thinking of using something else.

**Comment by andersonreloaded** [comment]
@netniV I am yet to send the script, however I've sent an email with the current progress on the script.
Waiting for your response.

**Comment by andersonreloaded** [comment]
I agree with @netniV.
@jpobeda It would be nice if you could  share possible set of improvements in the plugin. I have done some work on the plugin and already in discussion with @netniV and willing to contribute to the extent possible for making it a better plugin.

**Comment by netniV** [comment]
So, I've now committed a development that should work in both ways, plus you can now have the files moved out of the TFTP folder for security.  I'm testing this further but if anyone else feels like doing so, that would be appreciated 👍 

@chris-technicate - Don't bother, I'm doing it for you
@jpobeda - I've addd an option that's enabled by default but you should be able to untick it so you have the files in the archive directory you specify.
@andersonreloaded - Got your email, haven't responded yet, sounds interesting though I think we should continue that discussion off this issue :)

**Comment by andersonreloaded** [comment]
@netniV Shall test the development branch right away :)
I forgot that the original plugin unlinks (deletes) the copied configuration file after storing in the database.
However, the version which we have modified stores the configuration files appended with date-stamp under directories created with the device name.

**Comment by andersonreloaded** [comment]
@netniV The latest development branch worked like a charm! Thank you for the update.
Now I need to update SNMP based backup script :)

_**Off the topic:**_

- I had issues in setting up the tftp directory. Unless `chmod 777` is done for the directory, the files doesn't seem to get copied. Request if you have a working configuration without using `chmod 777` 
 
- The second input required is usage of telnet:// and ssh:// option in the plugin ?
 Earlier I remember using Cacti remote plugin.

**Comment by netniV** [comment]
For any off topic stuff, I would suggest creating a new issue, just so they can be answered, closed and searchable by others.

The backup (TFTP) path, the process that TFTP is running under will likely be different to the website/poller.  For example, on Ubuntu, I think TFTP runs as nobody, the website runs as Apache and the Poller runs as Cacti.  Thus, the backup location that TFTP sends to must be 777 to allow either the poller or the website to copy to the new Archive Path.  

If we wanted to leave the files in the TFTP directory, this could be reduced to 775, but I think it is best they are removed from there.

The alternative is to assign the cacti/website users to a group that is also used by the TFTP user and ‘chown’ or ‘chgrp’ the TFTP directory to use that.
