### ISSUE TITLE
form button save

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_routerconfigs#3]
The device and account edit forms will not save changes unless I comment out the a.linkOverDark event.preventDefault click action in include/layout.js.

Looking at syslog and thold, it appears you have created separate click functions for saving on those plugins?

**Comment by smiles1969** [comment]
I assume this is being done this way because you only want to refresh the changes with ajax/js from the form save and not have the whole page refresh, making the page response faster?

**Comment by cigamit** [comment]
Resolved
