### ISSUE TITLE
Make "device type" more customizable

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#33]
Till now we were using the very old "configstore" plugin with cacti 0.8.8b.
This old configstore plugin works with "expect" and exp files when backing up devices. It is very customizable because u can exactly define what output you expect when you are connected to the device and what you send to the switch/router.
When i put a bit time into the expect files, i am able to backup nearly every device via ssh/tftp.
For example: its possible to backup ibm flex systems or cisco nexus switches.

The championsleague feature update for routerconfigs would be a very customizable device type were you can freely define via webinterface what output you expect and what you want to send to the device.

greetings
seppel

**Comment by netniV** [comment]
Such a simple request, but please deposit £1,000,000 into my bank account so I can retire upon implementing this feature lol as that would be quite a bit of work.  

Being all the recent changes I've made to RCONFIG, I can see that working but it would need to be a big enhancement.  You'd have to do the following:

Method 1: Create many device type classes
- Update device type to have more connection types (currently in the latest live verison, that's SSH and Telnet)
- Create a ConnectionType abstract class and then update PHPTelnet, PHPSsh to be a subclass of that abstract class
- Create new ConnectionType based classes for things like FTP SFTP

Method 2: Switch to call a script that is called via popen() to read/write to

Both methods:
- Create LineResponses table which lists response to expect and whether it's a success or fail
- Create LineRequests table which lists requests to send which can be injected with variables (such as host, etc) 
- Create a Rules/Rules Item table which puts a sequence, optional flag and pointer to a Response or Request
   - eg: 
      - Rule 1, Item 1 - Type Request - ID: RequestID-1, Optional: No, Flag: Fail (used as default for response state)
      - Rule 1, Item 2 - Type Response - ID: ResponseID-1, Optional: Yes, Flag: None
      - Rule 1, Item 3 - Type Response - ID: ResponseID-2, Optional: No, Flag: Success
      - Rule 1, Item 4 - Type Request - ID: RequestID-2, Optional: Yes

Or something like that.  In truth, you probably need more conditionals to be able to group, etc.  A lot like Automation has.  That's quite a huge chunk of work but would, as you rightly point out, make it so much more flexible.

And then, you'd want to be able to export/import all that so you can share with others.

**Comment by seppeel** [comment]
> Such a simple request, but please deposit £1,000,000 into my bank account so I can retire upon implementing this feature lol as that would be quite a bit of work.

Haha, i will ask my employer to do that.

I know this is a very huge request, but maybe its possible to realize this sometime :-)

I think Method 2 is exactly what i was thinking about!
Making it possible to **backup** all devices will not be the only thing we have to take care about because we pull out data like "hostname" and "lastbackup". These data may be different or just not there.

Example IBM Flex System:
lastbackup: simply doesnt exist
the hostname is saved in quotation marks. and because routerconfigs will change the devices hostname in the database to the real hostname we will probably run into problems.

Im courious if this will be possible to realize :)

**Comment by netniV** [comment]
I'l add it to my 'features' list.  May be a while though lol

**Comment by rtripon** [comment]
Hello,
Anyone got this plugin working ? Every time I try to make it working, I run into different problems(best I could do was to run it manually, but automatically wasnt working).
Got the last devel source and here is my output:

��������
    |        |
   |||      |||
.:|||||:..:|||||:.
c2960
This is a secured device.
Unauthorized use is prohibited by law.
If you are not authorized to access this device please disconnect.


User Access Verification

Username: �� ������'��user
Password: 

c2960-POP#copy running-config tftp
Address or name of remote host []? y
Translating "y"

?Invalid host address or name
%Error parsing filename (Invalid IP address or hostname)
c2960-POP-Atrium#

For some reasons, the IP of the tftp server isnt aquired.

**Comment by netniV** [comment]
Which version of the plugin are you using? Also, please create a new issue if it's something specific and not the problem that's here.

**Comment by netniV** [comment]
With the 1.3 version that is waiting to be committed, I have created a based PHPConnection class.  At the moment, far too much is still handled by the _download() function but since we now have abstracted base class, there is nothing preventing me from now creating a 'test' class that simulates SSH/Telnet responses based off the buffers supplied by other people.  One step forward 👍

**Comment by seppeel** [comment]
Wow, thats nice :)

**Comment by seppeel** [comment]
I tried to bring Nexus devices into routerconfigs and its possible to do some things with workarounds:

I made routerconfigs able to connect and correctly login with username and password.
With an alias on the nexus, i was able to let routerconfigs copy the file via tftp to my cacti server

`cli alias name tftp copy running-config tftp://<tftpip>/<hostnameofswitch> vrf management`

-> Routerconfigs just types "tftp" instead of "copy run tftp" and the file is sent.

but then routerconfigs checks if there is a **valid** file.
 -> For routerconfigs its not valid and the backup fails :-)

Im very near to it :D

**Comment by netniV** [comment]
You should use 
```
copy running-config tftp://%SERVER%/%FILE% vrf management
```

This would remove the need for an alias, plus replaces the server name and filename dynamically.

**Comment by seppeel** [comment]
Thats right and works, too :-)
And i removed, that there is a confirmation and it works completeley!
i can backup nexus devices without any changes, nice!

**Comment by seppeel** [comment]
I closed the issue with hostname quotation marks as i am able to do IBM Flex backups now. For me everything is fine now, because i can backup everything i want.
But i still think its a good feature to make the device more customizable, i think we should keep this open?

**Comment by cigamit** [comment]
@netniV, your call.

**Comment by netniV** [comment]
I've added two more types (scp/sftp). Getting them to work properly may be interesting as my Cisco 1941 refused to play ball with either of them.  Maybe other people will be able to utilise them better.

PHP seems to do something in the background which causes an error relating to invalid parameters on the Cisco so it's probably device specific but also means it's not fully tested.
