### ISSUE TITLE
Cant install via git clone.

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_routerconfigs#37]
git clone https://github.com/Cacti/plugin_routerconfigs.git
Initialized empty Git repository in /var/www/html/cacti/plugins/plugin_routerconfigs/.git/
error:  while accessing https://github.com/Cacti/plugin_routerconfigs.git/info/refs

fatal: HTTP request failed

**Comment by netniV** [comment]
Most repo's just use the standard clone (without the .git), cacti plugins are an exception since The Cacti Group name all their plugin repos with the `plugin_` prefix.  Therefore, for any of their plugins, you also need to specify the correct plugin name.  Before doing ANY git clone, you have to also ensure that either the directory does not exist, or that it is empty:

To download:
```
cd plugins
git clone https://github.com/cacti/plugin_routerconfigs routerconfigs
```

To update:
```
cd plugins/routerconfigs
git pull
```

And there you go.  That will get you the latest development branch at the time of issues the pull.

Feel free to close this issue once you have successfully downloaded the sources.

**Comment by rtripon** [comment]
Hmmm...
What am I doing wrong ?

[root@cacti /]# cd /var/www/html/cacti/plugins/routerconfigs/
[root@cacti routerconfigs]# mkdir test
[root@cacti routerconfigs]# cd test
[root@cacti test]# git clone https://github.com/cacti/plugin_routerconfigs routerconfigs
Initialized empty Git repository in /var/www/html/cacti/plugins/routerconfigs/test/routerconfigs/.git/
error:  while accessing https://github.com/cacti/plugin_routerconfigs/info/refs

fatal: HTTP request failed

**Comment by netniV** [comment]
Do you have DNS on this box? Does this box have HTTPS access to the internet?

**Comment by rtripon** [comment]
Yes.

**Comment by netniV** [comment]
Then if you have copied and pasted my commands, there should be no issues.  You don't use a proxy server to access the internet do you?

**Comment by rtripon** [comment]
Nope, it's just an openvz machine. I have pings on any host.

**Comment by netniV** [comment]
What version of git are you using?

**Comment by rtripon** [comment]
1.7.1

On Feb 24, 2018 23:50, "netniV" <notifications@github.com> wrote:

What version of git are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cacti/plugin_routerconfigs/issues/37#issuecomment-368263064>,
or mute the thread

**Comment by netniV** [comment]
That will likely be your problem according to GitHub:
https://help.github.com/articles/https-cloning-errors/

They recommend 1.7.10 or above

**Comment by rtripon** [comment]
Great.. Now I got SSL connection error.

**Comment by netniV** [comment]
Can you post the full error?

**Comment by netniV** [comment]
I'm using 2.7.4, and I have no issues.

**Comment by rtripon** [comment]
I've updated to 2.x git version.

root@cacti routerconfigs]# cd test
      [root@cacti test]# git clone
https://github.com/cacti/plugin_routerconfigs routerconfigs
Cloning into 'routerconfigs'...
fatal: unable to access 'https://github.com/cacti/plugin_routerconfigs/':
SSL connect error
[root@cacti test]#

**Comment by netniV** [comment]
And the command was originally all on one line?

What happens if you use CURL or WGET on the url?

**Comment by rtripon** [comment]
Yes, one line.
root@cacti routerconfigs]# cd test
[root@cacti test]# wget https://github.com/cacti/plugin_routerconfigs
        --2018-02-25 00:27:55--
https://github.com/cacti/plugin_routerconfigs
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `plugin_routerconfigs'

    [  <=>                                     ] 74,733       268K/s   in
0.3s

2018-02-25 00:27:56 (268 KB/s) - `plugin_routerconfigs' saved [74733]

**Comment by netniV** [comment]
Hmm, try putting a .git on the end when you use the clone, see if that changes anything. It shouldn't.

**Comment by rtripon** [comment]
Same, but on another box with 1.7.12 version, all good. Git clone and pull
are working.
Seems that my git version is b0rken. Thanks for helping, I'll close the
issue.
Hopefully I can get back to 1.7.12 or something close, on this box.

**Comment by netniV** [comment]
I think your git version is fine, it's something else interfering.

**Comment by rtripon** [comment]
Closed for now, seems that its related to git version and not the plugin.
