### ISSUE TITLE
Backup interval

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_routerconfigs#4]
My backup interval is supposed to do daily backups, but it winds up only running every other day. Not sure what is up with the math calculating whether it should run or not with the poller. Is it possible to expose some of this in the settings so it can be set to run more frequently?

**Comment by cigamit** [comment]
Can you please attempt a pull request on this one?

**Comment by smiles1969** [comment]
Pull request submitted.

**Comment by smiles1969** [comment]
After a few days, the proposed change is consistently backing up nightly with a schedule of 1.

**Comment by cigamit** [comment]
I was looking at the code, and the reason that I have not merged it yet, is that I think that the logic is a bit dated.  It's your diff that is the problem, it's just the whole approach of detecting a long running backup.  Glad it's working, it may break again once I get some time to resolve the secondary issue.  Until then, I'm going to let that pull request sit a while.

**Comment by smiles1969** [comment]
I'm one of those old guys that prefers function over fashion. 😜

Sent from my iPhone

On Jan 13, 2017, at 5:34 AM, Jimmy Conner <notifications@github.com<mailto:notifications@github.com>> wrote:


I was looking at the code, and the reason that I have not merged it yet, is that I think that the logic is a bit dated. It's your diff that is the problem, it's just the whole approach of detecting a long running backup. Glad it's working, it may break again once I get some time to resolve the secondary issue. Until then, I'm going to let that pull request sit a while.

**Comment by cigamit** [comment]
This is resolved in 1.1
