### ISSUE TITLE
Create device type option "Hostname in config file is in quotation marks"

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#47]
The title explains what i want. This could allow the backup of IBM Flex devices.
Default format in Cisco IOS devices:
hostname <hostname>

in IBM Flex devices:
hostname "<hostname>"

**Comment by netniV** [comment]
To be honest, I don't think we should even bother with a device option.  Just need the match code to use a regular expression that allows optional quotes.

**Comment by netniV** [comment]
I think this works well, myself and reduces the code duplication.  If you run this using php -a, you can just paste in the following lines of code.

```php
 preg_match_all('~(host|set system )name ["]{0,1}([a-zA-Z0-9\._\-]+)["]{0,1}~','set hostname "test"',$matches);
var_dump($matches);
```
```php
 preg_match_all('~(host|set system )name ["]{0,1}([a-zA-Z0-9\._\-]+)["]{0,1}~','set hostname test',$matches);
var_dump($matches);
```
```php
 preg_match_all('~(host|set system )name ["]{0,1}([a-zA-Z0-9\._\-]+)["]{0,1}~','set hostname "@test"',$matches);
var_dump($matches);
```

**Comment by netniV** [comment]
This is now in v1.3.3 PR #50

**Comment by seppeel** [comment]
Seems like you always have the better ideas 👍 
this looks like a good way to do that. i will try to backup ibm flex stuff on monday.

**Comment by netniV** [comment]
Not better, just more experience with the code and how to be a little more generic 👍

**Comment by cigamit** [comment]
Merged now.  Close if remediated.

**Comment by netniV** [comment]
@seppeel Test this against your devices and see if it works for you.

**Comment by seppeel** [comment]
aaaand i successfully created ibm flex backups. great!
-> Closed.
