### ISSUE TITLE
Wrong counter for the devices tab

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#48]
I have 42 devices in my list.
When i have the first page opened the following is displayed:

1 to 20 of 42
and i have 3 pages of devices to browse. Everything ok so far.

BUT the first page displays 30 devices
 -> the second page 12 devices
 -> the third page is empty

:-)

**Comment by netniV** [comment]
As mentioned against your PR, I will correct this as there's more to fix than just changing the number 👍   The number probably works for you because that is your system default but it would fail for me.

**Comment by seppeel** [comment]
OK. I just saw the static number 30 and it was just logical for me, that the the rest is static, too.

**Comment by netniV** [comment]
Look up a couple of lines, and there's actually already code I put in.  That $num_rows line overrides that functionality, thus you aren't getting the right number of rows.  Try deleting it all together and it should start to work.

**Comment by netniV** [comment]
It's not merged yet but #50 is waiting in the wings.  If you want the latest version, you'll need to switch to my repo until @cigamit merges. (Edit the .git/config file to quickly change)

**Comment by seppeel** [comment]
Nah, i won't be able to test stuff before monday anyways. :)

**Comment by cigamit** [comment]
Merged now.  Close when confirmed.

**Comment by seppeel** [comment]
gooooood morning!

update to 1.3.3 -> NO devices are displayed
BUT the counter says 42 devices are there. i checked the DB and the devices are really there, only not displayed at all.

**Comment by seppeel** [comment]
```
05-03-2018 08:58:51 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
--
05-03-2018 08:58:51 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT * FROM plugin_routerconfigs_devices    ORDER BY hostname ASC  LIMIT 0, '
```

**Comment by netniV** [comment]
Yeah, already found and fixed this bug in 1.3.4 👍 

You can do one of two things, set the number of rows and they appear or take the 'S' off the `read_config_option('num_row_tables');` which believe it or not took me more than an hour of scratching my head wondering why this damn bug existed when it all looked correct compared to the backups tab!

**Comment by seppeel** [comment]
Removing the 'S' works :-)

What still remains:
when define a row setting in the cacti settings to something other than 20, the counter on top of the page is wrong (it always counts with 20).

**Comment by netniV** [comment]
Let me check on that.  That is probably down to what is being used by the API to build the table headings.  It may have a hard coded figure there.

**Comment by netniV** [comment]
Did you test this on the latest version ? It should be sorted now.

**Comment by seppeel** [comment]
Now, yes.
 -> Fixed and closed. Thanks!
