### ISSUE TITLE
Version 1.3.3 remote TFTP Server(directory)

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_routerconfigs#51]
Hello,
Is there a reason why I cant select the /var/lib/tftpboot on routerconfigs settings? I'm using a remote TFTP server and it wont let me select my tftpboot directory.
I can select another directory(like /var/www/html/cacti/, or /home/cacti/) but my TFTP server is started with /var/lib/tftpboot option. I've checked permissions(its 777 for the directory). I can start my tftpserver with that directory but I should be able to put /var/lib/tftpboot/ also, or?.

**Comment by rtripon** [comment]
Also, even if I set another directory, the plugin is looking locally for the directory/files and it will fail even 'tho the TFTP transfer is successful.

2018/03/03 18:15:49 - RCONFIG 172.25.232.62 (Telnet) -> Attempting to open socket to 172.25.232.62:23
2018/03/03 18:15:50 - RCONFIG 172.25.232.62 (Telnet) -> Looking for Username:
2018/03/03 18:15:52 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
2018/03/03 18:15:52 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Sending username: rtripon
2018/03/03 18:15:52 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Found Prompt (Password)
2018/03/03 18:15:52 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Found prompt 'Password:', Sending password: (16 chars)
2018/03/03 18:15:53 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Found Prompt (Enabled)
2018/03/03 18:15:53 - RCONFIG 172.25.232.62 (Telnet) -> NOTICE: Connected via telnet
2018/03/03 18:15:53 - RCONFIG 172.25.232.62 (Telnet) -> NOTICE: Already enabled, continuing
2018/03/03 18:15:53 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Prompt match (1) returned 1 matches
2018/03/03 18:15:53 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Sending confirmation: y
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Line: 0copy run tftp://217.156.98.102/TEBA
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Line: !!
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Line: 12409 bytes copied in 0.583 secs (21285 bytes/sec)
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Line: ro-ar01a-sw2960x-Teba#y
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Line:
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: Result: (0)

2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: TFP TRANSFER SUCCESSFUL
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> DEBUG: CHECKING FOR valid file at /home/cacti/TEBA
2018/03/03 18:15:54 - RCONFIG 172.25.232.62 (Telnet) -> ERROR: Failed to find file at /home/cacti/TEBA
2018/03/03 18:16:00 - RCONFIG NOTICE: Failed to download for TEBA
2018/03/03 18:16:00 - RCONFIG WARNING: 0 Devices Backed Up and 1 Devices Failed in 11 seconds
2018/03/03 18:16:00 - RCONFIG DEBUG: 0 devices backed up successfully.
2018/03/03 18:16:00 - RCONFIG DEBUG: 1 devices failed to backup.
2018/03/03 18:16:00 - RCONFIG DEBUG: These devices failed to backup
2018/03/03 18:16:00 - RCONFIG DEBUG: ------------------------------
2018/03/03 18:16:00 - RCONFIG DEBUG: TEBA - ERROR: TELNET no Config uploaded from Router
2018/03/03 18:16:01 - RCONFIG STATS: Time:11.74 Downloaded:0 Failed:1

**Comment by netniV** [comment]
There reason is that special folders are excluded from being used to prevent issues of overwriting important files.  So you have the following fields:

Field | Description
--- | ---
backup_root | This is where TFTP will drop the files (Settings -> Router Configs -> Backup Directory Path)
backup_folder | This is where RC will copy the file dropped into backup_root and current is expected to be a subdirectory of backup_root

So, if your backup_root is /tftp and your backup_folder for device1 is managed, and so is device2 then RC will place copy both files from `/tftp/<hostname>` to `/tftp/managed/<hostname>-<datetime>`

**Comment by rtripon** [comment]
Ok, got it. Thank you.

**Comment by netniV** [comment]
Cool.  Just for your reference, I updated the post slightly as it hid the fieldnames.
