### ISSUE TITLE
Report disabled devices via mail

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#52]
Make a third row in the mail:

- XX devices are disabled

**Comment by netniV** [comment]
Would you always want the number of devices skipped?  Since devices attempted (failed+success) would not necessarily be devices total even if we added +disabled

**Comment by seppeel** [comment]
Im not sure.
I configured routerconfigs to make backups at 00:00 and never retry
 -> The sum of success+failed+disabled should be devices total in this case. Thats perfect for me.

in other cases adding a +skipped could make sense

**Comment by netniV** [comment]
It should be, though there is a possibility that the next backup time for a device is beyond the next automated backup.  For example, if you manually update the dates.  Currently, there is no "Skip" option in the GUI, but in theory there's no reason why that couldn't be added if someone wanted it.

**Comment by netniV** [comment]
This is now in my repo for release with 1.3.4

**Comment by seppeel** [comment]
Which seems to be broken, because i just switched and get this  :-)


```
06-03-2018 13:28:31 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'
--
06-03-2018 13:28:31 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4629 cacti_debug_backtrace)
06-03-2018 13:28:31 - ERROR PHP PARSE in  Plugin 'routerconfigs': syntax error, unexpected 'NOTICE' (T_STRING), expecting ',' or ')' in file: /var/www/cacti/plugins/routerconfigs/functions.php on line: 173

```

**Comment by netniV** [comment]
Err, mine seems ok 😱 Did you update a second time  ? 😸

**Comment by seppeel** [comment]
Yes, my first pull idnt, get your ' syntax error ;-)
Its ok now.

**Comment by seppeel** [comment]
Looks great and can be closed :-)
