### ISSUE TITLE
Daily backup works every 2 days.

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_routerconfigs#57]
Hello,
I've noticed that even 'tho my setting are for daily backups, its done every 2 days. I dont really mind, but maybe someone would:).
Right now my columns look like this:
LAST ATTEMPT : 16.03.2018 23:00 ( which is the time backup worked).
NEXT BACKUP :  18.03.2018 22:00 ( which is a bit odd, since my settings are for daily 23:00 hours).

**Comment by netniV** [comment]
Is this still occurring?

**Comment by rtripon** [comment]
Yes. I don't really mind, that's why I didn't insist on the thread.

**Comment by deco521** [comment]
I can explain/clarify the issue that rtripon is seeing. With a successful daily scheduled backup, the next backup is being set to 24 hours + the scheduled time in the future. In the case above, the scheduled time is 23:00. The last backup was at 23:00 on 3/16/18. The calculated next backup is 3/16/18 + 24 hours = 3/17/18 + 23 (scheduled backup time) = 3/18/18 @22:00. My backups are scheduled @0200 and after a successful backup reschedule @0400.

**Comment by netniV** [comment]
Hmm, I'll look over the date logic.  It's supposed to take it back to midnight, then add on the offset.  Sounds like it's not taking it back to midnight.

**Comment by netniV** [comment]
This should now be fixed.  Please let me know if you think there are any more issues.

**Comment by deco521** [comment]
I think the date logic is still wonky :( My daily scheduled backups that ran this morning at 0200 (5/6/2018 02:00) set the next backup to tonight at 2200 (5/6/2018 22:00)

**Comment by netniV** [comment]
Could you do me a favour and run the following in mysql:
```sql
select * from settings where name like 'routerconfig%';
```

Also, what is your current timezone in UTC format?

**Comment by deco521** [comment]
# date
Sun May  6 12:40:07 EDT 2018
# date -u
Sun May  6 16:40:12 UTC 2018
# cat /etc/localtime
America/New_York

![routerconfigs](https://user-images.githubusercontent.com/38955476/39675674-05916f0c-514e-11e8-953d-e9afcbdf85ad.png)

**Comment by jdcoats** [comment]
This no longer happens.
