### ISSUE TITLE
Router Cant BACKUP

### ISSUE THREAD

**Issue by randymendes123** [Cacti/plugin_routerconfigs#58]
Hi all,
I need your help, i try to use this plugins to download Router backup config, but happnes the error below
--

2018/03/29 12:13:19 - CMDPHP PHP ERROR STRICT Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4595 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP STRICT in Plugin 'routerconfigs': Declaration of Text_Diff_Renderer_marker::_block() should be compatible with Text_Diff_Renderer::_block($xbeg, $xlen, $ybeg, $ylen, &$edits) in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 481
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 459
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 443
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 213
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 210
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 193
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 190
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 175
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 172
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 33 include_once)(/plugins/routerconfigs/router-compare.php: 33 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer.php on line: 120
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 33 include_once)(/plugins/routerconfigs/router-compare.php: 33 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer.php on line: 100
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 390
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 370
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 350
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 330

**Comment by netniV** [comment]
It sounds like you have PHP in strict mode.  What version of PHP are you using? What platform are you on? 

Most of the errors being reported are from the differencing engine which we don't control.

**Comment by netniV** [comment]
Sounds like you may have to do something like:
https://www.inmotionhosting.com/support/website/php/strict-standards-fix

**Comment by randymendes123** [comment]
Hi thanks,

[admin@LSVPRDICACTI02 ~]$ php -v
PHP 5.4.16 (cli) (built: Mar  7 2018 13:34:47)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

** CENTOS OS 7

**Comment by randymendes123** [comment]
Please any suggest to fix this issus ?

**Comment by netniV** [comment]
What is the value of the error_reporting option within your php.ini file? Remember there will likely be a separate PHP.INI for httpd and cli

**Comment by randymendes123** [comment]
Hi netNiv,
Now I´ve new issues, could you help me 


04/05/2018 03:11:22 PM - ROUTERCONFIGS: 10.66.165.18-> DEBUG: Connection failed
--
04/05/2018 03:11:22 PM - ROUTERCONFIGS: 10.66.165.18-> DEBUG: telnet
04/05/2018 03:11:21 PM - ROUTERCONFIGS: DEBUG: Telnet response:
2018/04/05 15:11:21 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 192 Connect)(/plugins/routerconfigs/functions.php: 887 fputs)(CactiErrorHandler)(/lib/functions.php: 4591 cacti_debug_backtrace)
2018/04/05 15:11:21 - ERROR PHP NOTICE in Plugin 'routerconfigs': fputs(): send of 2 bytes failed with errno=32 Broken pipe in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 887
04/05/2018 03:11:21 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:21 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:20 PM - ROUTERCONFIGS: DEBUG: Telnet response:
2018/04/05 15:11:20 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 192 Connect)(/plugins/routerconfigs/functions.php: 887 fputs)(CactiErrorHandler)(/lib/functions.php: 4591 cacti_debug_backtrace)
2018/04/05 15:11:20 - ERROR PHP NOTICE in Plugin 'routerconfigs': fputs(): send of 2 bytes failed with errno=32 Broken pipe in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 887
04/05/2018 03:11:20 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:20 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:19 PM - ROUTERCONFIGS: DEBUG: Telnet response:
2018/04/05 15:11:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devices.php: 135 actions_devices)(/plugins/routerconfigs/router-devices.php: 305 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 192 Connect)(/plugins/routerconfigs/functions.php: 887 fputs)(CactiErrorHandler)(/lib/functions.php: 4591 cacti_debug_backtrace)
2018/04/05 15:11:19 - ERROR PHP NOTICE in Plugin 'routerconfigs': fputs(): send of 2 bytes failed with errno=32 Broken pipe in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 887
04/05/2018 03:11:19 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:19 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:18 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:18 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:18 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:17 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:16 PM - ROUTERCONFIGS: DEBUG: No Prompt received
 
% Authentication failed
04/05/2018 03:11:16 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:15 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:14 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:14 PM - ROUTERCONFIGS: DEBUG: Telnet response:
username:
 
% Authentication failed
04/05/2018 03:11:12 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:12 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:12 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:10 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:09 PM - ROUTERCONFIGS: DEBUG: No Prompt received
username:
 
% Authentication failed
04/05/2018 03:11:09 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:08 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:07 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:07 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:05 PM - ROUTERCONFIGS: DEBUG: Telnet response:
04/05/2018 03:11:04 PM - ROUTERCONFIGS: DEBUG: No Prompt received
04/05/2018 03:11:04 PM - ROUTERCONFIGS: DEBUG: Telnet response:
 
 
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
G++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++G
G+++ DISCIPLINARES BEM COMO PROCEDIMENTO LEGAL CIVIL OU CRIMINAL +++G
G+++ TECNOLOGIAS DE INFORMACAO E COMUNICACOES PODERAO DESPOLETAR ACCOES +++G
G+++ COMPREENDE QUE AS VIOLACOES A POLITICA DE SEGURANCA A NIVEL DOS SISTEMAS E +++G
G+++ O UTILIZADOR RECONHECE QUE AS UTILIZACOES DESTE SISTEMA SAO REGISTADAS E +++G
G+++ AO CONTINUAR A USAR ESTE SISTEMA O UTILIZADOR RECONHECE QUE ESTA AUTORIZADO. +++G
G++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++G
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
 
Follow the installation instructions in the official manual at http://www.php.net/manual/en/ssh2.installation.php
04/05/2018 03:11:02 PM - ROUTERCONFIGS: 10.66.165.18-> DEBUG: PHP doesn't have the ssh2 module installed

**Comment by netniV** [comment]
This would mean that the device was not responding fully to telnet. You could install and enable the php-ssh module which will allow you to connect via SSH instead?

**Comment by netniV** [comment]
@randymendes123 did you get any further with this?

**Comment by netniV** [comment]
Closed due to lack of response.
