### ISSUE TITLE
Routerconfigs not working errors

### ISSUE THREAD

**Issue by randymendes123** [Cacti/plugin_routerconfigs#59]
Hi all,
I need your help, i try to use this plugins to download Router backup config, but happnes the error below
2018/03/29 12:13:19 - CMDPHP PHP ERROR STRICT Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4595 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP STRICT in Plugin 'routerconfigs': Declaration of Text_Diff_Renderer_marker::_block() should be compatible with Text_Diff_Renderer::_block($xbeg, $xlen, $ybeg, $ylen, &$edits) in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 481
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 459
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 443
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 213
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 210
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 193
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 190
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 175
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 34 include_once)(/plugins/routerconfigs/router-compare.php: 34 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line: 172
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 33 include_once)(/plugins/routerconfigs/router-compare.php: 33 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer.php on line: 120
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 33 include_once)(/plugins/routerconfigs/router-compare.php: 33 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer.php on line: 100
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 390
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 370
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 350
2018/03/29 12:13:19 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-compare.php: 32 include_once)(/plugins/routerconfigs/router-compare.php: 32 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/03/29 12:13:19 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Assigning the return value of new by reference is deprecated in file: /var/www/html/cacti/plugins/routerconfigs/Text/Diff.php on line: 330

**Comment by netniV** [comment]
You have already posted this issue as issue #58 so for now I am going to close this.  Please respond on the original issue thread.
