### ISSUE TITLE
Login Password being used when elevating via Enable

### ISSUE THREAD

**Issue by andersonreloaded** [Cacti/plugin_routerconfigs#61]
@netniV

With the original code, the back up is failing with "Error in authentication" reported in the Debug log. When I update the code with `$this->enablepw = $enablepw`; the back up is success. How the $pass and $enablepw take values from same variable. The constructor has two different arguments: $pass (assume its the login password) and $enablepw (enable password). Correct me if I am wrong. 

I think its a bug, which needs to be fixed!

**Comment by netniV** [comment]
It is! I was in a meeting so failed to look at it properly 🔫 

This should now be fixed.

**Comment by andersonreloaded** [comment]
@netniV 
Thank you for responding. I am a big fan of Cacti, just like you.
Have been using it for quite sometime (the pre 1.x.x releases).
Slowly migrating to 1.x.x and testing each plugin. I hope to contribute by testing, fixing few bugs and adding new plugins. Currently have CDP plugin, which is in some usable shape. Shall discuss if you are interested to contribute. 

Regards!

**Comment by andersonreloaded** [comment]
@netniV : I have fixed it my end :)

**Comment by netniV** [comment]
Sure.  Either add me as a collaborator/contributor or send me an email and we can talk there.

**Comment by andersonreloaded** [comment]
Sure, you can get in touch at anderson.reloaded@gmail.com

**Comment by andersonreloaded** [comment]
@netniV Thank you for the fix. The issue is closed.
