### ISSUE TITLE
Ensure correct action icons are displayed

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_routerconfigs#63]
I'd be nice to get these fixed.

It's always pointing to telnet:// even though you set connection type to be SSH.

![image](https://user-images.githubusercontent.com/13456559/38475558-202ba136-3bfd-11e8-9fba-218ecd1d7dc6.png)

To be honest I'd just remove them but maybe some people use them so..

**Comment by netniV** [comment]
That would be the way it's always worked.  I will take a look at some point to see if we can make it use SSH too.  It may even be already doing that just with the wrong title.

**Comment by netniV** [comment]
I just read this again and realise that you might prefer this as an option to remove it anyway?

**Comment by netniV** [comment]
This is now working by only showing those connect types that are applicable to a device.  If you have 'both' set, then it will show both telnet and SSH actions.
