### ISSUE TITLE
Comparison between devices is not working as expected

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#64]
Hi,

could you make deletitions red and insertions green? :)

**Comment by seppeel** [comment]
oh and i just noticed, that comparing between different devices does not work here, only if you select the same device on each side.

**Comment by netniV** [comment]
I am not sure if they were originally but when it moved to a newer version of the comparision library it definitely didn't colour them.  I did work on getting the compare working again but I haven't looked into the CSS styling (yet).

**Comment by netniV** [comment]
On the different device comparison front, can you explain why it doesn't work?  I'm not in front my work machine right now to check it.

**Comment by seppeel** [comment]
Oh, ok.
When i choose two different devices the page below "compare output" is just empty.

**Comment by netniV** [comment]
Are you using the latest release or develop branch?  Just so I know where I'm starting from.

**Comment by seppeel** [comment]
Yes, latest dev branch!

**Comment by netniV** [comment]
@seppeel this is now in the latest develop branch.
