### ISSUE TITLE
Hello Team

### ISSUE THREAD

**Issue by Bochi123** [Cacti/plugin_routerconfigs#66]
I have a problem with this plugins, I explain, I can't backup my router configuration with SSH.
It's working only with Telnet my version is : V0.3
My version of Cacti is 0.8.8h
Thnak you for your help :)

**Comment by netniV** [comment]
Your version of Cacti is to old for the current release of this plugin and has been for quite a number of years now. The last compatible version was 0.3.1 as noted here:
https://docs.cacti.net/plugin:routerconfigs
