### ISSUE TITLE
Support for more devices

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_routerconfigs#67]
Hey!
is it possible to upgrade routerconfigs to maintain all configured devices?
I always remove the whole directory, replace it with the new one and configure all devices from scratch.
Is there an easier way?

**Comment by andersonreloaded** [comment]
@Axel577 Can you please elaborate ? I didn't understand your requirement.

**Comment by Axel577** [comment]
@andersonreloaded 
My current version of routerconfigs is 1.1
The newest version provided here is 1.4
So I was wondering if it's possible to easily upgrade routerconfigs from 1.1 to 1.4. (and so on with newer versions in the future)
Until now, I removed the whole routerconfigs directory from /usr/share/cacti/site/plugins/, so it disappeared in cacti. Then I put the new version into /usr/share/cacti/site/plugins/ and installed the plugin again. But all my configured switches were lost, logically. I had to add them again.
You know what I mean?

**Comment by andersonreloaded** [comment]
@Axel577 
Recently I upgraded from 1.3 to 1.4 by replacing the entire directory and continued to use the plugin, however the devices list was not lost and remained intact. 
But one thing I didn't do is 're-installation of the plugin' through plugin management. May be that made a difference.
It must be a real pain to configure all devices from scratch :(

**Comment by netniV** [comment]
@Axel577 you should not have to reinstall a plugin just because you replace the code.  At the very most, the later versions of Cacti will only disable the plugin if an error occurs so that all you have to do is enable it again.  That should not lose your configuration.  In fact, routerconfigs will upgrade the database structure if it needs to for you too.

What version of cacti are you running?

**Comment by Axel577** [comment]
@netniV  I'm running cacti version 1.1.30.

**Comment by netniV** [comment]
Yeah pretty sure that it wouldn't force you to reinstall the plugin.  At the worst, it will just disable it if an error occurred.

**Comment by netniV** [comment]
One thing that would potentially be an issue.  From version 1.4, if you remove the existing folders, you remove the default archive location as that now sits beneath the plugin itself (/plugins/routerconfigs/backups/)

**Comment by Axel577** [comment]
I will keep that in mind, thanks for the hints.
