### ISSUE TITLE
routerconfigs Issues

### ISSUE THREAD

**Issue by randymendes123** [Cacti/plugin_routerconfigs#68]
Hi all
Please I need your support , I cant make backup on My Router cisco, could you help me 

2018/04/24 14:18:14 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-devices.php: 163 actions_devices)(/plugins/routerconfigs/router-devices.php: 334 plugin_routerconfigs_log)(/plugins/routerconfigs/functions.php: 910 CactiErrorHandler)(/lib/functions.php: 4579 cacti_debug_backtrace)
--
2018/04/24 14:18:14 - ERROR PHP RECOVERABLE_ERROR in Plugin 'routerconfigs': Argument 1 passed to plugin_routerconfigs_log() must be an instance of string, string given, called in /var/www/html/cacti/plugins/routerconfigs/router-devices.php on line 334 and defined in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 910

2018/04/24 14:18:14 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-devices.php: 163 actions_devices)(/plugins/routerconfigs/router-devices.php: 334 plugin_routerconfigs_log)(/plugins/routerconfigs/functions.php: 910 CactiErrorHandler)(/lib/functions.php: 4579 cacti_debug_backtrace)
--
2018/04/24 14:18:14 - ERROR PHP RECOVERABLE_ERROR in Plugin 'routerconfigs': Argument 1 passed to plugin_routerconfigs_log() must be an instance of string, string given, called in /var/www/html/cacti/plugins/routerconfigs/router-devices.php on line 334 and defined in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 910

![image](https://user-images.githubusercontent.com/32839066/39190163-e94a06aa-47cb-11e8-9ec6-d3ba670634a6.png)

![image](https://user-images.githubusercontent.com/32839066/39190270-27d8f516-47cc-11e8-8ea0-6690edf60853.png)

![image](https://user-images.githubusercontent.com/32839066/39190311-3c599edc-47cc-11e8-9c8e-3f14a806963d.png)

![image](https://user-images.githubusercontent.com/32839066/39190363-5df21ee8-47cc-11e8-8265-c6b1e3c026a2.png)

![image](https://user-images.githubusercontent.com/32839066/39190436-8179b24a-47cc-11e8-85b7-684682f4f18d.png)

If somenone already have this plugin working please help me !!!!

**Comment by andersonreloaded** [comment]
@randymendes123 
Which version of the plugin are you using ?
The suppose the issue reported got fixed recently. You need to upgrade the plugin to the latest version.
However don't re-install the plugin, just replace the old directory with the new version and start using.

**Comment by netniV** [comment]
Yes, this backtrace is out of date with the current development version so I can't really see what your issue is.  Please try upgrading and then see if the error goes away.

**Comment by randymendes123** [comment]
Hi  @andersonreloaded @netniV 
At moment i´ve 1.3.4 I think is the last version 
waiting your feedback.






--

**Comment by netniV** [comment]
The latest development version is 1.4. However, if you have that release I should be able to roll back and see if its something I fixed.

**Comment by netniV** [comment]
Yeah, that was already patch in 1.4.  If you don't want to upgrade, edit `functions.php` and change
```php
function plugin_routerconfigs_log(string $message, $log_level = POLLER_VERBOSITY_NONE) {
```

to 
```php
function plugin_routerconfigs_log($message, $log_level = POLLER_VERBOSITY_NONE) {
```

**Comment by randymendes123** [comment]
Hi @netniV 
the chenge was done , but O cant backup the configuration,

2018/04/25 14:00:03 - RCONFIG DEBUG: Executing '/bin/php' with arguments ' -q /var/www/html/cacti/plugins/routerconfigs/router-download.php --retry'

**Comment by randymendes123** [comment]
2018/04/25 14:04:36 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 155 edit_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 308 draw_edit_form)(/lib/html_form.php: 112 draw_edit_control)(/lib/html_form.php: 137 CactiErrorHandler)(/lib/functions.php: 4591 cacti_debug_backtrace)
--
2018/04/25 14:04:36 - ERROR PHP NOTICE: Undefined index: max_length in file: /var/www/html/cacti/lib/html_form.php on line: 137
2018/04/25 14:04:36 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 155 edit_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 308 draw_edit_form)(/lib/html_form.php: 112 draw_edit_control)(/lib/html_form.php: 137 CactiErrorHandler)(/lib/functions.php: 4591 cacti_debug_backtrace)
2018/04/25 14:04:36 - ERROR PHP NOTICE: Undefined index: max_length in file: /var/www/html/cacti/lib/html_form.php on line: 137

**Comment by netniV** [comment]
Upgrade to 1.4 😥

**Comment by randymendes123** [comment]
@netniV  could you send to me the link to download 1.4 , becouse on the release link just have v1.3
https://github.com/Cacti/plugin_routerconfigs/releases

**Comment by randymendes123** [comment]
@netniV  when I use  git clone -b master https://github.com/Cacti/plugin_monitor.git
just install the version 1.1 maybe need to update this link

![image](https://user-images.githubusercontent.com/32839066/39258016-d2a33266-48aa-11e8-87cf-b35a47ec5ae9.png)

**Comment by netniV** [comment]
Use the develop branch.  See how that fairs for you.  I'll get the master updated to the 1.3.4 release if that was the last one before the current.

**Comment by randymendes123** [comment]
@netniV is posible send to me the link to download the version 1.4
please I like CACTI so much and I wouldlike to have this plugins working in my side.

**Comment by netniV** [comment]
Use the clone or download button on the code section of the plugin site here on github:
https://github.com/Cacti/plugin_routerconfigs/archive/develop.zip

**Comment by randymendes123** [comment]
@netniV Thank you so much finally I´ve Plugin_routerconfigs working 100000% Fantastic!!! :):)
10000000 likes 😃

**Comment by netniV** [comment]
In that case, I"ll make it a full release. 👍
