### ISSUE TITLE
PHP 7.2 - each() is depreciated

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_routerconfigs#71]
Hey!
I have a new cacti 1.1.38 installation on an Ubuntu 18.04 system. I installed the newest version of routerconfigs. (1.4)

When I want to do a backup manually, I get in the cacti log:

2018/05/04 14:11:48 - ERROR PHP DEPRECATED in  Plugin 'routerconfigs': The each() function is deprecated. This message will be suppressed on further calls in file: /usr/share/cacti/site/plugins/routerconfigs/router-devices.php  on line: 318
2018/05/04 14:11:48 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-devices.php: 163 actions_devices)(/plugins/routerconfigs/router-devices.php: 318 each)(CactiErrorHandler)(/lib/functions.php: 4598 cacti_debug_backtrace)
2018/05/04 14:11:59 - RCONFIG 192.168.1.1 (SSH) -> ERROR: Failed to find file at /usr/share/cacti/site/plugins/routerconfigs/backups/switch
2018/05/04 14:12:01 - RCONFIG STATS: Time:12.48 Downloaded:0 Failed:1

**Comment by netniV** [comment]
This sounds like a PHP 7.2 error.  Is that what you are running?

**Comment by netniV** [comment]
This should now be resolved.  If you find any other PHP 7.2 related errors, please let me know in a new issue.
