### ISSUE TITLE
Backup time only showing latest backup time

### ISSUE THREAD

**Issue by deco521** [Cacti/plugin_routerconfigs#72]
When viewing backups using router-backups.php, all backups listed for a device show the same backup time (the lastbackup time) instead of the backup time of the actual backup.

![capture](https://user-images.githubusercontent.com/38955476/39663469-786b8b84-5063-11e8-95c7-f3a5accaec79.PNG)

I think line 351 should reference $row['btime'] instead of $row['lastbackup'] (for display on line 364).

Thanks!

**Comment by netniV** [comment]
If that's true, that's a good spot 👍

**Comment by netniV** [comment]
This should now be fixed if you could verify that.

**Comment by deco521** [comment]
Looks good.
Thanks!
