### ISSUE TITLE
Fail to connect Device using connection type: ssh

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_routerconfigs#75]
Hi team,

I cannot backup my Cisco switch. when I try to backup, it shows me the error as below:
![image](https://user-images.githubusercontent.com/11862935/42081756-79c0ad3e-7bb0-11e8-8c8c-69a6f76ba5e6.png)

**Comment by netniV** [comment]
Can you try enabling the debug mode and posting the results from that?  There will be more data including the name/ip of the device, any passwords are automatically masked.

**Comment by nhenpanha** [comment]
how to enable debug?

**Comment by netniV** [comment]
Settings -> RouterConfigs

**Comment by nhenpanha** [comment]
I go to RouterConfigs and tick Debug Connection Buffer than I do backup and go to the logs tab but didn’t see anything

**Comment by netniV** [comment]
Try doing it at the command line running router_download.php (I think it is)

```
php -q router_download.php <args>
```

If you are still struggling tomorrow I'll try and give you the full steps.

**Comment by nhenpanha** [comment]
Here is the result
![image](https://user-images.githubusercontent.com/11862935/42120088-7ff1b7c2-7c3f-11e8-97cf-ed323db47672.png)

**Comment by netniV** [comment]
Close, what we need is to add -b for debug buffer and you can also use -f to force a backup

**Comment by nhenpanha** [comment]
please help to check the debug:
![image](https://user-images.githubusercontent.com/11862935/42123538-0b1f977c-7c7e-11e8-81f6-89c122b4be3a.png)

**Comment by netniV** [comment]
OK, that was helpful as the answer is pretty simple.  You need to install and enable the PHP SSH2 module.

**Comment by nhenpanha** [comment]
![image](https://user-images.githubusercontent.com/11862935/42142208-40f2981c-7dd8-11e8-81e8-63f87db43af0.png)

**Comment by andersonreloaded** [comment]
@panhala Can you post the debug output after installation of SSH2 module as suggested by @netniV

**Comment by nhenpanha** [comment]
![image](https://user-images.githubusercontent.com/11862935/42145819-c388552c-7ded-11e8-817a-f192dc85d9d6.png)

**Comment by nhenpanha** [comment]
![image](https://user-images.githubusercontent.com/11862935/42145844-f47da4ca-7ded-11e8-8799-95deff33fe49.png)

**Comment by netniV** [comment]
OK so it would appear that your device didn't actually give notification that the connection dropped after hitting exit (or if it did it got lost in the post).  I would suggest disabling the option that sends exit before disconnect (i'm sure there is one but I can't check right now).

**Comment by nhenpanha** [comment]
It look like it cannot go to (enable mode) because I didn't configure any username and password at the enable mode....
![image](https://user-images.githubusercontent.com/11862935/42155115-adb785aa-7e11-11e8-8e93-0e7290ab2860.png)

**Comment by nhenpanha** [comment]
Now that's OK! Thanks for your always support....
