### ISSUE TITLE
Backup FortiGate

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_routerconfigs#76]
Is it possible to Backup FortiGate?

**Comment by netniV** [comment]
At the moment, Routerconfigs requires either SSH or Telnet to a device with TFTP commands to send the configuration back to the TFTP server running on the Cacti machine.  If FortiGate has the ability to TFTP a configuration, then yes.

There are plans in the near future to allow both SCP and a "show run" kind of capture of the configuration but that will be over the next month or so.

**Comment by nhenpanha** [comment]
We can ssh to fortigate by using

1. Input fortigate ip address
2. Input username and password

After that, issue below command to backup:

#config vdom
#edit root
#execute backup config tftp fortigate-file-name tftp-ip-address

Example: #execute backup config tftp fgt.cfg 192.168.3.11

**Comment by netniV** [comment]
I will investigate what we can do about this.  There are extra lines required to get to the backup command which means changing things or at least adding multiple entry boxes.

**Comment by nhenpanha** [comment]
do you have any update?

**Comment by netniV** [comment]
Sorry, we have been trying to the Core 1.2 out for the last few weeks so I haven't looked at any of the plugins.  Hopefully, that will be sorted over the next week and I can return my focus to this and some of the other plugin issues that have been reported.

**Comment by jdcoats** [comment]
you have to create a custom device-type with the commands needed. Then assign the device-type to the device.

Here is an example of some custom device types.

> MariaDB [cacti]> select * from plugin_routerconfigs_devicetypes;
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+
| id | name               | username | password | copytftp                                               | version      | confirm | forceconfirm | timeout | sleep |
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+
|  1 | Cisco IOS          | sername: | assword: | copy run tftp                                          | show version | y       |            0 |    NULL |  NULL |
|  2 | Cisco CatOS        | sername: | assword: | copy config tftp                                       |              | y       |            1 |    NULL |  NULL |
|  3 | ASA                | sername: | assword: | write net                                              | show version | y       |            1 |    NULL |  NULL |
|  4 | Nexus7K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf management vdc-all | show version | y       |            1 |    NULL |  NULL |
|  5 | Nexus5K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf management         | show version | y       |            1 |    NULL |  NULL |
|  6 | IBM Chassis Switch | sername: | assword: | copy run tftp filename %FILE% address 10.9.76.48 mgt   | show version | y       |            0 |    NULL |  NULL |
|  7 | Nexus9K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf default vdc-all    | show version | y       |            1 |    NULL |  NULL |
| 99 | Fortigate          | sername: | assword: | tftp-backup                                            |              | y       |            1 |       0 |     0 
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+


as far as the multiple lines you just create an alias on the fortigate like shown here:
[https://help.fortinet.com/fos50hlp/54/Content/FortiOS/fortigate-whats-new-54/FeatureCatalog-system.htm](url)

create an alias called something like tftp-backup that issues the specific commands you need run and then create the device-type something like shown below using a unique id

> insert into plugin_routerconfigs_devicetypes value ('99', 'Fortigate', 'sername:', 'assword:', 'tftp-backup', '', 'y', '1', '', '' );

**Comment by honcheongwong** [comment]
I used this plug-in to backup the customer's Fortinet firewall, but the debug log shows that cannot find the prompt for delivered the backup command at all.  With checked on the code, I guess the prompt is not recognized by plug-in module as a space character is found between the host name and the '#' character.  How can I get resolve this barrier to carry on backup the Forinet firewall configure?  Please advice.

Part of the debug log is shown as below:
=========================
2019/05/15 11:45:39 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: <-- XXXXXFW01 # 
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: Attempt 10 of 10 to find prompt
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> Process is now NOT enabled
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: --> exit
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: <-- exit
2019/05/15 11:45:40 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: <-- 
2019/05/15 11:45:41 - RCONFIG 99.99.99.99 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
2019/05/15 11:45:41 - RCONFIG NOTICE: Failed to download for XXXXXFW01
2019/05/15 11:45:41 - RCONFIG WARNING: 1 Devices Backed Up, 1 Devices Failed, 0 Disabled (ignored) in 21 seconds

**Comment by netniV** [comment]
Can you email me the full log to developers@cacti.net?

**Comment by honcheongwong** [comment]
Yes.  The caption debug log had been sent to developers@cacti.net and attached below:

[Palo-FW-config-download-dump.txt](https://github.com/Cacti/plugin_routerconfigs/files/3240050/Palo-FW-config-download-dump.txt)
[FortiNET-FW-config-download-dump.txt](https://github.com/Cacti/plugin_routerconfigs/files/3240051/FortiNET-FW-config-download-dump.txt)

It seem to the plugin cannot found the proper enable command prompt to input the command.  

With Best Regards,

HC Wong

**Comment by honcheongwong** [comment]
Dear CACTI developers professional(s),

   The full debug log from the CACTI system is attached for your reference.  Thanks.

   The issue is seem to be the routerconfigs plugin do not placed the backup command to the device because of it cannot found the proper enable command prompt  to issue command (enable command prompt should be with ‘#’ mark right after hostname with no space character).

With Best Regards,

HC Wong
