### ISSUE TITLE
Truncated backups

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_routerconfigs#77]
Cisco device backups are being truncated if I do not check the "Check end in config" check box for the device type. When I do check that box, backups fail with error code 5 (bad download of config). At first I thought it might be the preg_match in functions.php line 327 looking for the regular expression '/\n[^\w]*end[^\w]*$/' but nothing I did seemed to make it any better.

**Comment by ghost** [comment]
Extending the default sleep time seems to help alleviate this, but that seems arbitrary. Would rather that the "check end in config" worked.

**Comment by netniV** [comment]
The check end in config does not truncate backups whether it's on or off.  It merely checks whether a backup was complete by making sure the word 'end' is on a new line without any whitespaces around it.

**Comment by ghost** [comment]
Understood. What I'm saying is that with check end in config turned on, backups are failing with error code 5 (bad download of config). With it turned off, backups were truncated until I extended the default sleep time. It seemed to me that the logical way to handle this was to check the box to make it look for "end" so it could tell that the config was complete. However, this was not working. I'll try again today with longer default sleep time and with check end in config enabled.

**Comment by ghost** [comment]
With "check end in config" enabled for the device type and the default sleep time and default timeout extended, it seems to be working. However, now we're getting backup failures on scheduled backups. On-demand backups work well.

**Comment by netniV** [comment]
The check end doesn't actually extend the time before it completes, it merely checks that the backup was actually successfully transmitted with an "end" line at the end which is normal for Cisco backups.

If it fails to find that, it would still fail the backup.  Curious as to why the file would fail on the regex, would you be willing to share that privately for me to test against?

**Comment by netniV** [comment]
On the scheduled front, if you are still having issues, create a separate issue for that.

**Comment by ghost** [comment]
I can share privately to test. It seems that I'm still occasionally running into issues with "bad download of config" if I turn on "check end in config".

**Comment by netniV** [comment]
Can you send the configuration to netniv@cacti.net ? I will try and see why this would fail.  If you could ensure that you transfer it in binary mode from the backup location on the cacti server, that will ensure that I get it as it was transferred.

**Comment by ghost** [comment]
As you have said, the timeout value and the "check end in config" are unrelated. The "check end in config" is working as expected. Where I'm getting anomalies is when I have a device either on a slow connection or using too much of its CPU. This causes the device to timeout responding to the router-backups.php script. When that happens, I get a partially downloaded configuration which does not have the "end" in it.

End result is that if I enable "check end in config" it is correctly saying that it didn't get it, because it didn't. The config was truncated because of the slow connection or slow response from the device. Closing this issue once and for all. No need to send the config, because it works as long as it gets a complete configuration file in the TFTP directory.

**Comment by netniV** [comment]
Good to know there's no bug and that it's working as expected, thanks!
