### ISSUE TITLE
Manual and Schedule backup

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_routerconfigs#78]
Hi team,

when i did manual backup, it worked normally but 
when I did schedule backup every 12 hours and tick "seperate by device" option, it show me the fail message. Please help me?

thanks in advance...

**Comment by netniV** [comment]
Can you get the debug log for the scheduled backup?  The scheduled backup runs as the polling user not the website user so you could always run a simulation by running the backup process with the poller user at command line.

**Comment by ghost** [comment]
This helped me. I failed to recognize that the scheduled backups run as the poller user. Seems obvious in hindsight, but setting the archive directory permissions to account for this made my scheduled backups work.
