### ISSUE TITLE
Configuration viewer does not utilise full width due to incorrect style

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#79]
The main config viewer is narrow and wraps configs, its sort of ugly. It should be wider to utilize more of the page and not wrap configs at so few characters.
![screen shot 08-17-18 at 09 16 am](https://user-images.githubusercontent.com/42470924/44268651-a7584300-a221-11e8-96e7-e34aedb7b1cc.PNG)

**Comment by netniV** [comment]
Can you let me know the last part of the URL and the parameters so I can narrow down which bit of code to check?

**Comment by jdcoats** [comment]
/cacti/plugins/routerconfigs/router-devices.php?action=viewconfig&id=323

**Comment by netniV** [comment]
This should now be resolved.  IF you pull down router-devices.php it contains the corrected style tag that overrides the textarea class in main.css (which the core provides).
