### ISSUE TITLE
routerconfigs 1.4 adds a trailing colon to mac addresses

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#80]
when searching for mac addresses this is misleading since you cannot find any mac using "matches" and the actual mac since the data is stored as something like 18:03:73:4A:4D:56: with a trailing colon.

**Comment by netniV** [comment]
Router configs does not do anything with Mac Addresses, can you give the steps you are taking to do this?

**Comment by jdcoats** [comment]
I just downloaded the development routerconfigs zip and the problem still exists.
