### ISSUE TITLE
Backups fail for random switches using SSH

### ISSUE THREAD

**Issue by Teebor** [Cacti/plugin_routerconfigs#81]
I've looked at similar issues but none that seem to be open or closed for this exact issue.  Apologies if I overlooked a previously raised issue.

I am trying to backup around 18 switches and out of these only 2 have this problem.

The errors in the Cacti logs appear as:
08/30/2018 15:23:22 - RCONFIG 172.27.0.45 (SSH) -> ERROR: Failed to open file at /opt/cacti-1.1.38/backups/LG_8Port_Sw

Now this looks like a simple file access issue however bear with me.
Here are the steps I am seeing to replicate this issue and the current workaround.

1) No file exists in the TFTP directory to start
2) Cacti connects to the switch and successfully copies the file to the TFTP server (File now exists in the directory with nobody as the owner) this can be seen as successfully copied to TFTP server in the debug for the switch and checking the local directory manually.
3) Error above then appears in cacti log, however this is for only the problem switches the other 16ish switches work correctly using SSH (same models of switch and same connection method/authentication)
4) I can access, modify, move and delete the file freely from the CLI, admittedly as root

Workaround:
Change the connection method for the problem switch to TELNET from SSH

I have tried changing the connection type to BOTH however this then throws the same error presumably as the switch is reachable via SSH and copies the file to the TFTP server successfully?

Now I'm assuming that the procedure is the same whether using TELNET or SSH and the file is sent via TFTP to the same directory?

I can access all the switches manually using SSH and I can copy the running config to the TFTP server.

I have tried deleting the switch entry from router configs within Cacti and then recreating it and the problem follows the specific switch.  I also deleted the switch entry and created a couple of entries for some more switches of the same make model and similar running configuration and they worked OK - but I'm not ruling out something on that specific switch, I just can't see what it is at the moment.

The two switches that have the problem are different models but both are from Cisco and both run different firmware versions due to the difference in model type.

As an additional note the problem switches only allowed SSH access so I have had to temporarily add TELNET access to allow cacti to backup the config from these switches.  I would like to remove TELNET access as soon as I can.

Also before upgrading to the latest Cacti version I was using CactiEZ which I think is 0.8.8 on CentOS6? and the router configs plugin was able to backup these same switches up without an issue.
I have since then installed an updated OS with a newer CentOS installation along with Cacti version 1.1.38

Running OS:  centos-release-7-5.1804.el7.centos.x86_64
OS Type: 64 Bit
Cacti Version: 1.1.38
Router configs version: 1.4.0
Cacti is a VM running on Hyper-V
PHP Version: PHP 7.1.20 (cli) (built: Jul 20 2018 08:31:34) ( NTS )

**Comment by netniV** [comment]
The chances are it's a problem with the SSH server on the switches themselves.  I have some HP switches which when operating via SSH hang when closing the connection.  In the automated world, something like that would generate a timeout error and thus stop the rest of the process from working.

It would be useful if you could get a full debug of what is occurring for one of the problem devices.

**Comment by Teebor** [comment]
Please ignore the 1 hour time difference, the Cacti server is running on BST but I keep the switches on UTC so there is a 1 hour difference at this time of year.

Please see below from the switch side:
Sep  3 09:13:11.613: SSH1: starting SSH control process
Sep  3 09:13:11.613: SSH1: sent protocol version id SSH-1.99-Cisco-1.25
Sep  3 09:13:11.613: SSH1: protocol version id is - SSH-2.0-libssh2_1.4.3 PHP
Sep  3 09:13:11.613: SSH2 1: SSH2_MSG_KEXINIT sent
Sep  3 09:13:11.622: SSH2 1: SSH2_MSG_KEXINIT received
Sep  3 09:13:11.622: SSH2:kex: client->server enc:aes256-cbc mac:hmac-sha1
Sep  3 09:13:11.630: SSH2:kex: server->client enc:aes256-cbc mac:hmac-sha1
Sep  3 09:13:11.899: SSH2 1: expecting SSH2_MSG_KEXDH_INIT
Sep  3 09:13:11.907: SSH2 1: SSH2_MSG_KEXDH_INIT received
Sep  3 09:13:12.385: SSH2: kex_derive_keys complete
Sep  3 09:13:12.385: SSH2 1: SSH2_MSG_NEWKEYS sent
Sep  3 09:13:12.385: SSH2 1: waiting for SSH2_MSG_NEWKEYS
Sep  3 09:13:12.410: SSH2 1: SSH2_MSG_NEWKEYS received
Sep  3 09:13:12.620: SSH2 1: Using method = none
Sep  3 09:13:12.628: SSH2 1: Using method = keyboard-interactive
Sep  3 09:13:12.637: SSH2 1: authentication successful for admin
Sep  3 09:13:12.637: SSH2 1: channel open request
Sep  3 09:13:12.645: SSH2 1: pty-req request
Sep  3 09:13:12.645: SSH2 1: setting TTY - requested: height 25, width 80; set: height 25, width 80
Sep  3 09:13:12.654: SSH2 1: shell request
Sep  3 09:13:12.654: SSH2 1: shell message received
Sep  3 09:13:12.654: SSH2 1: starting shell for vty
Sep  3 09:13:13.677: SSH1: Session terminated normally

Directory of TFTP location:
[root@localhost ~]# ls -o /opt/cacti-1.1.38/backups/
total 12
-rw-rw-rw- 1 nobody 3947 Sep  3 10:13 LG_8Port_Sw

Cacti Log file:
09/03/2018 10:13:14 - RCONFIG STATS: Time:3.11 Downloaded:0 Failed:1
09/03/2018 10:13:13 - RCONFIG 172.27.0.45 (SSH) -> ERROR: Failed to open file at /opt/cacti-1.1.38/backups/LG_8Port_Sw

Debug info from plugin page for problem switch:
LG_8Port_Sw#
LG_8Port_Sw#copy run tftp
Address or name of remote host []? [IP HIDDEN]
Destination filename [lg_8port_sw-confg]? LG_8Port_Sw
!!
3947 bytes copied in 0.503 secs (7847 bytes/sec)
LG_8Port_Sw#

Comparison with a working switch of the same model:
GND_8Port_Sw3#
GND_8Port_Sw3#copy run tftp
Address or name of remote host []? [IP HIDDEN]
Destination filename [gnd_8port_sw3-confg]? GND_8Port_Sw3
!!
8386 bytes copied in 0.520 secs (16127 bytes/sec)
GND_8Port_Sw3#

**Comment by netniV** [comment]
Yeah, that looks good from a manual point of view. Can you get the full debug log from router configs too?

**Comment by Teebor** [comment]
I'm starting to get out of my knowledge zone now but I think this is the correct information?

Still looks like a file access permission issue, but it successfully identifies and removes the original file?


09/03/2018 11:13:01 - RCONFIG NOTICE: Starting manual backup of 1 devices
09/03/2018 11:13:01 - RCONFIG DEBUG: SQL: SELECT * FROM plugin_routerconfigs_devices WHERE enabled = 'on' AND id IN (11)
09/03/2018 11:13:01 - RCONFIG DEBUG: Attempting download for LG_8Port_Sw
09/03/2018 11:13:01 - RCONFIG DEBUG: Base64 decoded: a:3:{i:543504209;i:834003048;s:8:"password";s:7:"(7: chars)";i:719212604;i:1126341987;}
09/03/2018 11:13:01 - RCONFIG DEBUG: Base64 decoded:
09/03/2018 11:13:01 - RCONFIG DEBUG: Attempting to remove pre-existing incoming file: /opt/cacti-1.1.38/backups/LG_8Port_Sw
09/03/2018 11:13:01 - RCONFIG [SWITCH IP] -> DEBUG: Attempting to connect via SSH
09/03/2018 11:13:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Creating SSH(Server: [SWITCH IP], User: [Admin USER], Password: (7 chars), Enablepw: (Not Set), Devicetype: {"id":"1","name":"Cisco IOS","username":"username:","password":"password:","copytftp":"copy run tftp","version":"show version","confirm":"y","sleep":"125000","timeout":"1","forceconfirm":"on","checkendinconfig":""}
09/03/2018 11:13:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Setting timeout to 1 second(s)
09/03/2018 11:13:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Setting sleep time to 125000 microsecond(s)
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: okay: logged in...
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Connected via ssh
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Ensuring process is enabled
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: -->
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- LG_8Port_Sw#
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- LG_8Port_Sw#
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Enabled)
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> Process is now enabled
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> copy run tftp
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- copy run tftp
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- Address or name of remote host []?
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Question)
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: copy run tftp
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: Address or name of remote host []?
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Question found
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Sending Server: [SERVER IP]
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> [SERVER IP]
09/03/2018 11:13:02 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- [SERVER IP 1st OCTET]
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- [SERVER IP 2nd, 3rd, 4th OCTECT]
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- Destination filename [lg_8port_sw-confg]?
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Question)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: [SERVER IP]
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: Destination filename [lg_8port_sw-confg]?
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Question found
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Sending Filename (Destination): LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- !
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- !
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- 3938 bytes copied in 0.696 secs (5658 bytes/sec)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- LG_8Port_Sw#
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Enabled)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: !!
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: 3938 bytes copied in 0.696 secs (5658 bytes/sec)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: LG_8Port_Sw#
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Checking for valid incoming file at /opt/cacti-1.1.38/backups/LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> ERROR: Failed to open file at /opt/cacti-1.1.38/backups/LG_8Port_Sw
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> exit
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <-- exit
09/03/2018 11:13:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: <--
09/03/2018 11:13:04 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Timeout of 1 seconds has been reached
09/03/2018 11:13:04 - RCONFIG NOTICE: Failed to download for LG_8Port_Sw
09/03/2018 11:13:04 - RCONFIG WARNING: 0 Devices Backed Up, 1 Devices Failed, 0 Disabled (ignored) in 3 seconds
09/03/2018 11:13:04 - RCONFIG DEBUG: 0 devices backed up successfully.
09/03/2018 11:13:04 - RCONFIG DEBUG: 1 devices failed to backup.
09/03/2018 11:13:05 - RCONFIG STATS: Time:3.86 Downloaded:0 Failed:1

**Comment by netniV** [comment]
The folder above called `/opt/cacti-1.1.38/backups/` is the location where your TFTP server defaults to?  This would suggest it's a local file permission issue.  Also, make sure there is not a directory of the same name as the file in that folder.  That will also cause issues.

**Comment by Teebor** [comment]
This is the current folder status:

[root@localhost ~]# ls -o /opt/cacti-1.1.38/backups/
total 4
-rw-rw-rw- 1 nobody 3938 Sep  3 11:13 LG_8Port_Sw

[root@localhost ~]# ls -ld /opt/cacti-1.1.38/backups/
drwxrwxrwx 2 apache apache 25 Sep  3 11:13 /opt/cacti-1.1.38/backups/

However if this was a folder permission issue would this not affect the other devices? For example here is a debug from a working switch that stores the file in the same directory:

[root@localhost ~]# php /opt/cacti-1.1.38/plugins/routerconfigs/router-download.php --debug --device 12
09/03/2018 11:30:58 - RCONFIG NOTICE: Starting manual backup of 1 devices
09/03/2018 11:30:58 - RCONFIG DEBUG: SQL: SELECT * FROM plugin_routerconfigs_devices WHERE enabled = 'on' AND id IN (12)
09/03/2018 11:30:58 - RCONFIG DEBUG: Attempting download for GND_8Port_Sw3
09/03/2018 11:30:58 - RCONFIG DEBUG: Base64 decoded: a:3:{i:527404211;i:834263118;s:8:"password";s:7:"(7: chars)";i:750111422;i:1216441187;}
09/03/2018 11:30:58 - RCONFIG DEBUG: Base64 decoded:
09/03/2018 11:30:58 - RCONFIG [SWITCH IP] -> DEBUG: Attempting to connect via SSH
09/03/2018 11:30:58 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Creating SSH(Server: [SWITCH IP], User: [ADMIN ACCOUNT], Password: (7 chars), Enablepw: (Not Set), Devicetype: {"id":"1","name":"Cisco IOS","username":"username:","password":"password:","copytftp":"copy run tftp","version":"show version","confirm":"y","sleep":"125000","timeout":"1","forceconfirm":"on","checkendinconfig":""}
09/03/2018 11:30:58 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Setting timeout to 1 second(s)
09/03/2018 11:30:58 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Setting sleep time to 125000 microsecond(s)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: okay: logged in...
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Connected via ssh
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Ensuring process is enabled
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: -->
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Enabled)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> Process is now enabled
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> copy run tftp
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Question)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: copy run tftp
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: Address or name of remote host []?
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Question found
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Sending Server: [SERVER IP]
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> [SERVER IP]
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Question)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: [SERVER IP]
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: Destination filename [gnd_8port_sw3-confg]?
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Question found
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> NOTICE: Sending Filename (Destination): GND_8Port_Sw3
09/03/2018 11:31:00 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> GND_8Port_Sw3
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Timeout of 1 seconds has been reached
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: GND_8Port_Sw3
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: !!
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (8)
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Sending a return
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: -->
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Found Prompt (Enabled)
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line:
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: 8441 bytes copied in 1.267 secs (6662 bytes/sec)
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: GND_8Port_Sw3#
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Line: GND_8Port_Sw3#
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Result: (0)
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Checking for valid incoming file at /opt/cacti-1.1.38/backups/GND_8Port_Sw3
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Attempting to open file at /opt/cacti-1.1.38/backups/GND_8Port_Sw3
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Configuration end check was not performed
09/03/2018 11:31:01 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: --> exit
09/03/2018 11:31:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Timeout of 1 seconds has been reached
09/03/2018 11:31:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Configuration Data Length 8454
09/03/2018 11:31:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Checking backup directory exists: /opt/cacti-1.1.38/plugins/routerconfigs/backups/
09/03/2018 11:31:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Attempting to backup to filename '/opt/cacti-1.1.38/plugins/routerconfigs/backups/GND_8Port_Sw3-2018-09-03-1131'
09/03/2018 11:31:03 - RCONFIG [SWITCH IP] (SSH) -> DEBUG: Backed up
09/03/2018 11:31:03 - RCONFIG NOTICE: Download successful for GND_8Port_Sw3
09/03/2018 11:31:03 - RCONFIG NOTICE: 1 Devices Backed Up, 0 Devices Failed, 0 Disabled (ignored) in 5 seconds
09/03/2018 11:31:03 - RCONFIG DEBUG: 1 devices backed up successfully.
09/03/2018 11:31:03 - RCONFIG DEBUG: 0 devices failed to backup.
09/03/2018 11:31:03 - RCONFIG STATS: Time:4.10 Downloaded:1 Failed:0

**Comment by Teebor** [comment]
Oh and sorry I forgot to say that yes this is the TFTP default directory for the inbound files

**Comment by netniV** [comment]
And you are sure there is not a directory of the same name as the configuration file?

**Comment by Teebor** [comment]
Also for comparison the same device but using TELNET instead, no other changes

php /opt/cacti-1.1.38/plugins/routerconfigs/router-download.php --debug --device 11
<CUT FOR BREVITY>
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> NOTICE: Sending Server: [SERVER IP]
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: --> [SERVER IP]
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Found Prompt (Question)
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: [SERVER IP]
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: Destination filename [lg_8port_sw-confg]?
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Result: (0)
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Question found
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> NOTICE: Sending Filename (Destination): LG_8Port_Sw
09/03/2018 13:08:21 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: --> LG_8Port_Sw
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Found Prompt (Enabled)
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: LG_8Port_Sw
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: !!
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: 8051 bytes copied in 0.520 secs (15483 bytes/sec)
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Line: LG_8Port_Sw#
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Result: (0)
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Checking for valid incoming file at /opt/cacti-1.1.38/backups/LG_8Port_Sw
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Attempting to open file at /opt/cacti-1.1.38/backups/LG_8Port_Sw
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Configuration end check was not performed
09/03/2018 13:08:22 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: --> exit
09/03/2018 13:08:23 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
09/03/2018 13:08:23 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Configuration Data Length 8320
09/03/2018 13:08:23 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Checking backup directory exists: /opt/cacti-1.1.38/plugins/routerconfigs/backups/
09/03/2018 13:08:23 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Attempting to backup to filename '/opt/cacti-1.1.38/plugins/routerconfigs/backups/LG_8Port_Sw-2018-09-03-1308'
09/03/2018 13:08:23 - RCONFIG [SWITCH IP] (Telnet) -> DEBUG: Backed up
09/03/2018 13:08:23 - RCONFIG NOTICE: Download successful for LG_8Port_Sw
09/03/2018 13:08:23 - RCONFIG NOTICE: 1 Devices Backed Up, 0 Devices Failed, 0 Disabled (ignored) in 5 seconds

**Comment by netniV** [comment]
OK leave this with me to ponder and I'll come back to you.

**Comment by Teebor** [comment]
No worries, its a weird issue for sure.

I expect it might not be something that can be solved and maybe nobody else will see it.  But if you need any more info let me know and I will give you what I can.

Tree view of part of the folder structure:
[root@localhost ~]# tree /opt/cacti-1.1.38/
/opt/cacti-1.1.38/
├── about.php
├── aggregate_graphs.php
├── aggregate_items.php
├── aggregate_templates.php
├── auth_changepassword.php
├── auth_login.php
├── auth_profile.php
├── automation_devices.php
├── automation_graph_rules.php
├── automation_networks.php
├── automation_snmp.php
├── automation_templates.php
├── automation_tree_rules.php
├── backups
├── boost_rrdupdate.php
├── cache
│   ├── boost
│   │   └── index.php
│   ├── index.php
│   ├── mibcache
│   │   └── index.php
│   ├── realtime
│   │   └── index.php
│   └── spikekill
│       └── index.php


There could be a hidden file/folder but I can't see it :D


I would also like to take the opportunity for saying thanks for maintaining such a useful tool, it has helped me out many times.

**Comment by netniV** [comment]
I noticed that you were running these from the command line as root, you should run them as the poller user and see if that makes any differences whilst I'm still trying to see what would be different.

**Comment by netniV** [comment]
I'm wondering if this is a timing issue.  You see the code in question is this:

```php
$file = false;
$data = false;
if (!file_exists("$readname")) {
        $connection->Log("ERROR: Failed to find file at $readname");
} else {
        if (filesize("$readname") > 0) {
                $connection->Log("DEBUG: Attempting to open file at $readname");
                $file = @fopen("$readname", 'r');
        }

        if ($file === false) {
                $connection->Log("ERROR: Failed to open file at $readname");
        } else {
                $data = @fread($file, filesize("$readname"));
                @fclose($file);

                if ($data === false) {
                        $connection->Log("ERROR: Failed to read file at $readname");
                }
        }
}

if ($data === false) {
        $connection->error(7);
```

So, because it failed to find the file, it errors.  If the device in question is not releasing the file/connection to the TFTP server properly, it may not yet be visible to the rest of the file system (exclusive locks and all that).

I'll see about adding a "pause" after disconnecting.  It means shifting some code around because the existing stuff expects to stay connected a while longer to get some other information, but I don't see why that can't be shuffled around.

**Comment by netniV** [comment]
As part of #87 and #65, I've rejigged the code, see if this works for you.
