### ISSUE TITLE
[develop] - Manually backup doesn't work

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_routerconfigs#84]
![cacti005](https://user-images.githubusercontent.com/11805503/46470555-b7cb7980-c7df-11e8-8b6f-2977db174478.gif)

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version
- Backtrace
- Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by pautiina** [comment]
- OS & Version: FreeBSD 11.2-STABLE
- PHP Version: PHP 7.0.30 (cli) (built: Jul 4 2018 11:18:07) ( NTS )
- Cacti Version: [ 1.2.0 - Beta 1 ]
- Plugin version 1.4.0 - develop branch

There are no errors in the log files.
In this case, when backup is done through poller - everything is fine.
When I manually start a command from the server console, backup is done successfully.

**Comment by netniV** [comment]
When running the command manually, are you using `sudo -u <username>` in front of the `php` command so that it runs as the website user?

**Comment by pautiina** [comment]
I'm use: `su -m www`

**Comment by netniV** [comment]
There are debug settings, try setting those to see if more information comes about.

**Comment by pautiina** [comment]
On my gif two windows are shown. The second window shows just the debug information on the plugin.

**Comment by netniV** [comment]
There should be a lot more than that.

![image](https://user-images.githubusercontent.com/9052188/46476064-26f49e00-c7df-11e8-8312-8d679ac167b5.png)

**Comment by pautiina** [comment]
With disabled option:
```
2018/10/04 16:15:05 - RCONFIG DEBUG: Executing manual backup using '/usr/local/bin/php' with arguments ' -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1'
2018/10/04 16:15:05 - POLLER: Poller[1] DEBUG: About to Spawn a Remote Process [CMD: /usr/local/bin/php, ARGS:  -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1]

```
With enabled option:
```
2018/10/04 16:16:25 - RCONFIG DEBUG: Executing manual backup using '/usr/local/bin/php' with arguments ' -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1'
2018/10/04 16:16:25 - POLLER: Poller[1] DEBUG: About to Spawn a Remote Process [CMD: /usr/local/bin/php, ARGS:  -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1]
```

**Comment by netniV** [comment]
OK, try this... add the following as the first line of function `plugin_routerconfigs_download()` in functions.php:

```php
cacti_log("plugin_routerconfigs_download($retry, $force, array(" . implode(',',$devices) . "), $buffer_debug, $simulate);");
```

**Comment by netniV** [comment]
Then you should be able to run it through the web browser and see that being hit.  If it's not being hit, then something is stopping inside router-download.php before it gets there... if so, add cacti_log("a number"); at various points to see where it gets up to (start after the first include/global.php)

**Comment by pautiina** [comment]
> OK, try this... add the following as the first line of function `plugin_routerconfigs_download()` in functions.php:
> 
> ```
> cacti_log("plugin_routerconfigs_download($retry, $force, array(" . implode(',',$devices) . "), $buffer_debug
> ```

I add this line on function plugin_routerconfigs_download and run manualy backup, but nothing happens.
```
function plugin_routerconfigs_download($retry = false, $force = false, $devices = array(), $buffer_debug = false, $simulate = false) {
	cacti_log("plugin_routerconfigs_download($retry, $force, array(" . implode(',',$devices) . "), $buffer_debug, $simulate);");
	ini_set('max_execution_time', '0');
	ini_set('memory_limit', '256M');

```
Now I will add additional logging сacti_log("a number");

**Comment by pautiina** [comment]
I add line ` cacti_log("ROUTERCONFIG: LINE75")` on router-download.php after include/global.php and run manualy backup but bothing happens.

Look for thiscode on file `router-devices.php`:

```
	if (sizeof($device_array)) {
		if (get_nfilter_request_var('drp_action') == '1') { /* Backup */
			$command_string = trim(read_config_option('path_php_binary'));

			if (trim($command_string) == '') {
			        $command_string = 'php';
			}

			$extra_args = ' -q ' . $config['base_path'] . '/plugins/routerconfigs/router-download.php' .
				' --devices=' . implode(',',$device_array);

			plugin_routerconfigs_log(__("DEBUG: Executing manual backup using '%s' with arguments '%s'",$command_string,$extra_args,'routerconfigs'));
			exec_background($command_string, $extra_args, true);
			header('Location: router-devices.php?header=false');
			exit;
		}
	}
```

I think problem here

**Comment by netniV** [comment]
Let see if I can get this setup at work tomorrow...

**Comment by netniV** [comment]
Maybe put use `file_put_contents()` function at top of router-download.php writing to new file in cacti log folder. If it appears script is spawn, otherwise somethings wrong with that section you noted.

**Comment by pautiina** [comment]
I looked at this part of the code again - everything is fine with this code.
The parameters of this code are passed to the exec_background function, as evidenced by an entry in the log: 
` POLLER: Poller[1] DEBUG: About to Spawn a Remote Process [CMD: /usr/local/bin/php, ARGS:  -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1]`
but why this command doesn’t go further - I don’t understand.

**Comment by pautiina** [comment]
The command does not reach the router-download.php file.
I try change code for this:
```

	if (sizeof($device_array)) {
		if (get_nfilter_request_var('drp_action') == '1') { /* Backup */
			$command_string = trim(read_config_option('path_php_binary'));

			if (trim($command_string) == '') {
			        $command_string = 'php';
			}

			$extra_args = ' -q ' . $config['base_path'] . '/plugins/routerconfigs/router-download.php' .
				' --devices=' . implode(',',$device_array);

			plugin_routerconfigs_log(__("DEBUG: Executing manual backup using '%s' with arguments '%s'",$command_string,$extra_args,'routerconfigs'));
			//exec_background($command_string, $extra_args, true);
			$log = shell_exec('/usr/local/bin/php -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1');
			cacti_log("ROUTERCONFIG: $log");
			header('Location: router-devices.php?header=false');
			exit;
		}
	}
```
but log empty:

```
2018/10/04 23:11:01 - RCONFIG DEBUG: Executing manual backup using '/usr/local/bin/php' with arguments ' -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1'
2018/10/04 23:11:01 - CMDPHP ROUTERCONFIG:

```

**Comment by netniV** [comment]
Is that the correct path to PHP?

**Comment by netniV** [comment]
Add  ` &2>1` to the shell command  inside the quotes (note the space)

**Comment by pautiina** [comment]
> Is that the correct path to PHP?

correct

**Comment by pautiina** [comment]
> Add `&2>1` to the shell command inside the quotes (note the space)

Change cod for this:
```
	//exec_background($command_string, $extra_args, true);
			$log = shell_exec('/usr/local/bin/php -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1 &2>1 ');
			cacti_log("ROUTERCONFIG: $log");
			cacti_log("ROUTERCONFIG: COMMAND: /usr/local/bin/php -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1 &2>1 ");
```
On cacti log:
```
2018/10/04 23:59:59 - RCONFIG DEBUG: Executing manual backup using '/usr/local/bin/php' with arguments ' -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1'
2018/10/04 23:59:59 - CMDPHP ROUTERCONFIG:
2018/10/04 23:59:59 - CMDPHP ROUTERCONFIG: COMMAND: /usr/local/bin/php -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1 &2>1
```

Change code for this:
```
			//exec_background($command_string, $extra_args, true);
			$log = shell_exec('/usr/local/bin/php -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1 &2>1 ');
			$log2 = shell_exec('uname -a');
			cacti_log("ROUTERCONFIG: $log");
			cacti_log("ROUTERCONFIG: $log2");
```
cacti log:
```
2018/10/05 00:04:06 - RCONFIG DEBUG: Executing manual backup using '/usr/local/bin/php' with arguments ' -q /var/www/cacti/plugins/routerconfigs/router-download.php --devices=1'
2018/10/05 00:04:06 - CMDPHP ROUTERCONFIG:
2018/10/05 00:04:06 - CMDPHP ROUTERCONFIG: FreeBSD noc.isp.kh.ua 11.2-STABLE FreeBSD 11.2-STABLE #0 r337890M: Thu Aug 16 11:24:23 EEST 2018     pautina@noc.isp.kh.ua:/usr/obj/usr/src/sys/NOC  amd64

```

**Comment by netniV** [comment]
Put an echo first line of router-download.php

Also try php -l router-download.php

**Comment by netniV** [comment]
Oh try asking PHP for its version too

**Comment by netniV** [comment]
I think I've found the cause.

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by pautiina** [comment]
Thanks, fixed
