### ISSUE TITLE
device types tab displays blank page and says Permission Denied

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#85]
![screen shot 10-26-18 at 02 26 pm](https://user-images.githubusercontent.com/42470924/47585676-ff02e100-d92b-11e8-9058-860eae09f27a.PNG)

**Comment by jdcoats** [comment]
cacti 1.1.38 and current dev routerconfigs

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by jdcoats** [comment]
# uname -a
Linux 4.9.76-gentoo-r1 #1 SMP Tue Feb 13 15:23:37 EST 2018 x86_64 Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz GenuineIntel GNU/Linux

# php -v
PHP 7.0.30 (cli) (built: Aug 20 2018 17:48:56) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30, Copyright (c) 1999-2017, by Zend Technologies

Version 1.1.38 | (c) 2004-2018 - The Cacti Group

  | Routerconfigs | 1.4.0

I do not see any errors in the webserver log or cacti log when this happens.

**Comment by netniV** [comment]
Is it when you first click routerconfigs or when you click any tab?.

**Comment by jdcoats** [comment]
only the Device Types tab. The other 4 tabs (Devices, Authentication, Backups, Compare) work fine.

**Comment by netniV** [comment]
I could not replicate this error until I took away the Router Configs permission under users->User->Edit->Permissions.  Once I did that, then I saw what you see.  

Can you make sure that your user does have the appropriate rights for Router Configs?  I will also see if I can replicate this any other way.
