### ISSUE TITLE
Login stalls due to "Press Any Key" styled prompt

### ISSUE THREAD

**Issue by wazwz** [Cacti/plugin_routerconfigs#87]
Hi, 

The prompt can't be find after login (mostly with HP devices) due to  "Press any key to continue" .

It seems that an option need to send after the login.

```console
2019/01/21 09:32:42 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Attempt 2 of 10 to find prompt
2019/01/21 09:32:42 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Timeout of 10 seconds has been reached
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: -->
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Timeout of 10 seconds has been reached
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: -->
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> NOTICE: Ensuring process is enabled
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Connected via ssh
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: okay: logged in...
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Setting sleep time to 125000 microsecond(s)
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Setting timeout to 10 second(s)
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Creating SSH(Server: HOST, User: Username, Password: (11 chars), Enablepw: (11 chars), Devicetype: {"username":"username:","password":"password:","copytftp":"copy running-config tftp","version":"show version","sleep":"125000","timeout":"1","forceconfirm":"","checkendinconfig":"on"}
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 -> DEBUG: Attempting to connect via SSH | 
2019/01/21 09:32:42 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Attempt 2 of 10 to find prompt
2019/01/21 09:32:42 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Timeout of 10 seconds has been reached
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: -->
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
2019/01/21 09:32:32 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Timeout of 10 seconds has been reached
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: -->
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> NOTICE: Ensuring process is enabled
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Connected via ssh
2019/01/21 09:32:22 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: okay: logged in...
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Setting sleep time to 125000 microsecond(s)
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Setting timeout to 10 second(s)
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 (SSH) -> DEBUG: Creating SSH(Server: HOST, User: Username, Password: (11 chars), Enablepw: (11 chars), Devicetype: {"username":"username:","password":"password:","copytftp":"copy running-config tftp","version":"show version","sleep":"125000","timeout":"1","forceconfirm":"","checkendinconfig":"on"}
2019/01/21 09:32:21 - RCONFIG 10.234.130.231 -> DEBUG: Attempting to connect via SSH
```

Regards.

**Comment by netniV** [comment]
So I formatted your post for you.  This is definitely a feature enhancement that is needed.  I will hopefully have some time in the next week or so to do some plugin work that is sorely needed.

**Comment by wazwz** [comment]
Hi, is there any good news ?

**Comment by netniV** [comment]
I've been off ill this week but the plan is to get back in the saddle this weekend.  I'm thinking I'll be starting with this plugin.

**Comment by wazwz** [comment]
Hi, I hope that you're doing well, look forward to hear about any good news. Thank you.

**Comment by netniV** [comment]
I've rejigged the code, see if this works for you.

**Comment by wazwz** [comment]
Hi, 

After the check it seems that it's not able to find the prompt, with this error : 

2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284

2019/02/19 15:47:33 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: -->
--
2019/02/19 15:47:33 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Attempt 3 of 10 to find prompt
2019/02/19 15:47:33 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Timeout of 5 seconds has been reached
2019/02/19 15:47:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:28 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:28 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: -->
2019/02/19 15:47:28 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Attempt 2 of 10 to find prompt
2019/02/19 15:47:28 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Timeout of 5 seconds has been reached
2019/02/19 15:47:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:23 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:23 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: -->
2019/02/19 15:47:23 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
2019/02/19 15:47:23 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Timeout of 5 seconds has been reached
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-download.php: 133 plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 159 plugin_routerconfigs_download_config)(/plugins/routerconfigs/functions.php: 499 EnsureEnabled)(/plugins/routerconfigs/classes/PHPConnection.php: 134 DoCommand)(/plugins/routerconfigs/classes/PHPConnection.php: 229 GetResponse)(/plugins/routerconfigs/classes/PHPConnection.php: 284 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 15:47:18 - ERROR PHP NOTICE in Plugin 'routerconfigs': Undefined index: AnyKey in file: /usr/share/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 284
2019/02/19 15:47:18 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: -->
2019/02/19 15:47:18 - RCONFIG 10.234.254.14 (SSH) -> NOTICE: Ensuring process is enabled
2019/02/19 15:47:18 - RCONFIG 10.234.254.14 (SSH) -> DEBUG: Connected via ssh

**Comment by netniV** [comment]
Have you ensured that your version number updated?  This sounds like an upgrade issue.

**Comment by wazwz** [comment]
The version shown is 1.4.1

**Comment by wazwz** [comment]
Here the message I got, when I try to create a new device type.

```
2019/02/19 16:17:41 - DBCALL ERROR: SQL Save Failed for Table 'plugin_routerconfigs_devicetypes'. SQL:'INSERT INTO plugin_routerconfigs_devicetypes (`id`, `name`, `username`, `password`, `copytftp`, `version`, `confirm`, `forceconfirm`, `checkendinconfig`, `timeout`, `sleep`, `anykey`) VALUES (0, 'HP Procurve', 'username:', 'password:', 'copy running-config tftp', 'show version', '', '', '', 1, 125000, 'Press any key to continue') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `username`=VALUES(`username`), `password`=VALUES(`password`), `copytftp`=VALUES(`copytftp`), `version`=VALUES(`version`), `confirm`=VALUES(`confirm`), `forceconfirm`=VALUES(`forceconfirm`), `checkendinconfig`=VALUES(`checkendinconfig`), `timeout`=VALUES(`timeout`), `sleep`=VALUES(`sleep`), `anykey`=VALUES(`anykey`)'
--
2019/02/19 16:17:41 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-devtypes.php: 159 save_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 280 sql_save)(/lib/database.php: 1002 _db_replace)(/lib/database.php: 949 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
2019/02/19 16:17:41 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'anykey' in 'field list'
2019/02/19 16:17:41 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO plugin_routerconfigs_devicetypes (`id`, `name`, `username`, `password`, `copytftp`, `version`, `confirm`, `forceconfirm`, `checkendinconfig`, `timeout`, `sleep`, `anykey`) VALUES (0, 'HP Procurve', 'username:', 'password:', 'copy running-config tftp', 'show version', '', '', '', 1, 125000, 'Press any key to continue') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `username`=VALUES(`username`), `password`=VALUES(`password`), `copytftp`=VALUES(`copytftp`), `version`=VALUES(`version`), `confirm`=VALUES(`confirm`), `forceconfirm`=VALUES(`forceconfirm`), `checkendinconfig`=VALUES(`checkendinconfig`), `timeout`=VALUES(`timeout`), `sleep`=VALUES(`sleep`), `anykey`=VALUES(`anykey`)'
2019/02/19 16:17:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 159 save_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 280 sql_save)(/lib/database.php: 979 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 16:17:41 - ERROR PHP NOTICE: Undefined index: anykey in file: /usr/share/cacti/lib/database.php on line: 979
2019/02/19 16:17:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 159 save_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 280 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 16:17:41 - ERROR PHP NOTICE: Undefined index: anykey in file: /usr/share/cacti/lib/database.php on line: 978
2019/02/19 16:17:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 159 save_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 280 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 16:17:41 - ERROR PHP NOTICE: Undefined index: anykey in file: /usr/share/cacti/lib/database.php on line: 977
2019/02/19 16:17:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/routerconfigs/router-devtypes.php: 159 save_devicetypes)(/plugins/routerconfigs/router-devtypes.php: 280 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2019/02/19 16:17:41 - ERROR PHP NOTICE: Undefined index: anykey in file: /usr/share/cacti/lib/database.php on line: 976
```

**Comment by netniV** [comment]
Can you run 
```sql
show create table plugin_routerconfigs_devicetypes\G
```

**Comment by wazwz** [comment]
```
*************************** 1. row ***************************
       Table: plugin_routerconfigs_devicetypes
Create Table: CREATE TABLE `plugin_routerconfigs_devicetypes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) DEFAULT NULL,
  `username` varchar(64) DEFAULT NULL,
  `password` varchar(256) DEFAULT NULL,
  `copytftp` varchar(64) DEFAULT NULL,
  `version` varchar(64) DEFAULT NULL,
  `confirm` varchar(64) DEFAULT NULL,
  `sleep` int(11) DEFAULT NULL,
  `timeout` int(11) DEFAULT NULL,
  `forceconfirm` char(2) DEFAULT 'on',
  `checkendinconfig` char(2) DEFAULT 'on',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COMMENT='Router Config Device Types'
1 row in set (0.00 sec)
```

**Comment by netniV** [comment]
Right, you are definitely missing a column there. Did you upgrade or install from scratch?

**Comment by netniV** [comment]
The original issue has been resolved, this additional issue has been recorded separately
