### ISSUE TITLE
Undefined index: checkendinconfig on line 624 & 633

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#89]
2019/01/29 13:00:40 - ERROR PHP NOTICE in  Plugin 'routerconfigs': Undefined index: checkendinconfig in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/functions.php  on line: 624
2019/01/29 13:00:40 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/functions.php[154]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/functions.php[624]:CactiErrorHandler())
2019/01/29 13:00:40 - ERROR PHP NOTICE in  Plugin 'routerconfigs': Undefined index: checkendinconfig in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/functions.php  on line: 633
2019/01/29 13:00:40 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/functions.php[154]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/functions.php[633]:CactiErrorHandler())

**Comment by netniV** [comment]
What version of routerconfigs are you running?

**Comment by netniV** [comment]
Do you have an associated devicetype set against your device?

**Comment by jdcoats** [comment]
1.4.0 current commit. Most devices are set to auto but I have a few device-types configured for IBM, Nexus, and ASA devices. The DeviceTypes "tab" hasn't worked since upgrade to the 1.x versions It just says permission denied. The plugin itself works and the other tabs work, Its just throwing errors in the log and the device types are not accessible from the gui. 
![untitled2](https://user-images.githubusercontent.com/42470924/52164865-4c7ab100-26c6-11e9-8e49-bd88cf591e5b.png)
I have to manipulate the device types directly at the database.
`MariaDB [cacti]> describe plugin_routerconfigs_devicetypes;
+--------------+--------------+------+-----+---------------+----------------+
| Field        | Type         | Null | Key | Default       | Extra          |
+--------------+--------------+------+-----+---------------+----------------+
| id           | int(12)      | NO   | PRI | NULL          | auto_increment |
| name         | varchar(128) | NO   |     | NULL          |                |
| username     | varchar(64)  | NO   |     | sername:      |                |
| password     | varchar(128) | NO   |     | assword:      |                |
| copytftp     | varchar(64)  | NO   |     | copy tftp run |                |
| version      | varchar(64)  | NO   |     | show version  |                |
| confirm      | varchar(64)  | NO   |     |               |                |
| forceconfirm | int(1)       | NO   |     | NULL          |                |
| timeout      | int(18)      | YES  |     | NULL          |                |
| sleep        | int(18)      | YES  |     | NULL          |                |
+--------------+--------------+------+-----+---------------+----------------+
10 rows in set (0.01 sec)

MariaDB [cacti]> show table status where NAME='plugin_routerconfigs_devicetypes';
+----------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
| Name                             | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation          | Checksum | Create_options | Comment |
+----------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
| plugin_routerconfigs_devicetypes | InnoDB |      10 | Compact    |    8 |           2048 |       16384 |               0 |            0 |         0 |            100 | 2019-01-22 09:53:29 | NULL        | NULL       | utf8mb4_unicode_ci |     NULL |                |         |
+----------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
1 row in set (0.02 sec)

MariaDB [cacti]> select * from plugin_routerconfigs_devicetypes;
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+
| id | name               | username | password | copytftp                                               | version      | confirm | forceconfirm | timeout | sleep |
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+
|  1 | Cisco IOS          | sername: | assword: | copy run tftp                                          | show version | y       |            0 |    NULL |  NULL |
|  2 | Cisco CatOS        | sername: | assword: | copy config tftp                                       |              | y       |            1 |    NULL |  NULL |
|  3 | ASA                | sername: | assword: | write net                                              | show version | y       |            1 |    NULL |  NULL |
|  4 | Nexus7K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf management vdc-all | show version | y       |            1 |    NULL |  NULL |
|  5 | Nexus5K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf management         | show version | y       |            1 |    NULL |  NULL |
|  6 | IBM Chassis Switch | sername: | assword: | copy run tftp filename %FILE% address 10.9.76.48 mgt   | show version | y       |            0 |    NULL |  NULL |
|  7 | Nexus9K            | sername: | assword: | copy run tftp://%SERVER%/%FILE% vrf default vdc-all    | show version | y       |            1 |    NULL |  NULL |
| 99 | Fortigate          | sername: | assword: | tftp-backup                                            |              | y       |            1 |    NULL |  NULL |
+----+--------------------+----------+----------+--------------------------------------------------------+--------------+---------+--------------+---------+-------+
8 rows in set (0.00 sec)
`

**Comment by netniV** [comment]
Go to Console -> configuration -> users -> (edit yourself) -> Permissions, and make sure you have all the routerconfig permissions.

**Comment by jdcoats** [comment]
![screen shot 02-04-19 at 08 27 am](https://user-images.githubusercontent.com/42470924/52211144-00ab4180-2857-11e9-98b4-3eb9fcf9f57e.PNG)

**Comment by jdcoats** [comment]
I fixed the tab issue. For some reson the router-devtypes.php wasn't in the realm and would not update with the setup.php.

> |  42 | routerconfigs | router-devices.php,router-accounts.php,router-backups.php,router-compare.php   

> UPDATE `plugin_realms` SET `file` = 'router-devices.php,router-accounts.php,router-backups.php,router-compare.php,router-devtypes.php' WHERE `plugin_realms`.`id` = 42

I also had to add the column checkendinconfig manually

**Comment by netniV** [comment]
That sounds like an upgrade didn't go through that should have.
