### ISSUE TITLE
Warnings in apache logs

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_routerconfigs#9]
My routerconfigs plugin is fully functional, however I am getting these in my apache error log:

[Fri Jan 13 09:54:56.433863 2017] [:error] [pid 9831] [client 192.168.11.140:53883] PHP Strict Standards:  Declaration of Text_Diff_Renderer_marker::_block() should be compatible with Text_Diff_Renderer::_block($xbeg, $xlen, $ybeg, $ylen, $edits) in /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line 0, referer: http://192.168.11.15/cacti/plugins/routerconfigs/router-compare.php?tab=compare
[Fri Jan 13 09:54:56.517928 2017] [:error] [pid 9831] [client 192.168.11.140:53883] PHP Warning:  Creating default object from empty value in /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line 391, referer: http://192.168.11.15/cacti/plugins/routerconfigs/router-compare.php?tab=compare
[Fri Jan 13 09:54:56.519787 2017] [:error] [pid 9831] [client 192.168.11.140:53883] PHP Warning:  Creating default object from empty value in /var/www/html/cacti/plugins/routerconfigs/Text/Diff/Renderer/table.php on line 359, referer: http://192.168.11.15/cacti/plugins/routerconfigs/router-compare.php?tab=compare

**Comment by cigamit** [comment]
The Horde Text_Diff library is out of date, and will need an update, which means that there will be some other more dramatic changes.  You will have to wait a bit on this one I'm afraid.

**Comment by cigamit** [comment]
See my other note on this.  It's related to the request I made for you.

**Comment by smiles1969** [comment]
This would be done, except I couldn't find a way to get the side by side view (table view) on the new Horde. There was no table view function in the new Horde.

**Comment by cigamit** [comment]
Still open.

**Comment by cigamit** [comment]
Should be resolved now.
