### ISSUE TITLE
Saving files on remote TFTP server

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_routerconfigs#92]
Hello,
I'm having some troubles trying to save my configs to a remote server. If I try manually, the file is copied, but then the script is looking for a local file on a local path and obviously is missing.
On my settings page (the IP is from remote server) is  allowing me to save only local path : e.g. /var/www/html/cacti/
If I try to enter the path from the remote server, I cant save. I know I'm doing something wrong :).
I have the last version from  git.

2019/02/27 12:13:46 - RCONFIG 10.57.11.16 -> DEBUG: Attempting to connect via Telnet
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Creating Telnet(Server: 10.57.11.16, User: admin, Password: (8 chars), Enablepw: (Not Set), Devicetype: {"id":"1","name":"Cisco IOS","username":"username:","password":"password:","copytftp":"copy run tftp","version":"show version","confirm":"y","sleep":null,"timeout":null,"forceconfirm":"","checkendinconfig":"on","anykey":""}
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Setting timeout to 1 second(s)
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Setting sleep time to 125000 microsecond(s)
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> Disconnect()
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> Attempting to open socket to 10.57.11.16:23
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> Looking for username:
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- ��������CC
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <--     |        |
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <--    |||      |||
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- .:|||||:..:|||||:.
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP UPC-Astral - Arad
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- This is a secured device.
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- Unauthorized use is prohibited by law.
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- If you are not authorized to access this device please disconnect.
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- User Access Verification
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- Username: �� ������'��
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Username)
2019/02/27 12:13:46 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Sending username: admin
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- admin
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- Password: 
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Password)
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Sending password: (8 chars)
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:47 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> NOTICE: Connected via telnet
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> NOTICE: Already enabled, continuing
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> copy run tftp
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- copy run tftp
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- Address or name of remote host []? 
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Question)
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: copy run tftp
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: Address or name of remote host []? 
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Result: (0)
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Question found
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> NOTICE: Sending Server: 172.25.232.33
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> 172.25.232.33
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 172.25.232.33
2019/02/27 12:13:48 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- Destination filename [sw2960-cx-testlacp-confg]? 
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Question)
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: 172.25.232.33
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: Destination filename [ar-sw2960-cx-testlacp-confg]? 
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Result: (0)
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Question found
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> NOTICE: Sending Filename (Destination): SW-OFFICE
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> SW-OFFICE
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW-OFFICE
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- !!
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 10541 bytes copied in 0.276 secs (38192 bytes/sec)
2019/02/27 12:13:49 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: SW-OFFICE
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: !!
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: 10541 bytes copied in 0.276 secs (38192 bytes/sec)
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Line: SW2960-CX-TESTLACP#
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Result: (0)
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> terminal length 0
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- terminal length 0
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> terminal pager 0
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- terminal pager 0
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <--                                  ^
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- % Invalid input detected at '^' marker.
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:50 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:51 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/02/27 12:13:51 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
2019/02/27 12:13:51 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> show version
2019/02/27 12:13:52 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/02/27 12:13:52 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
PHP Notice:  Undefined variable: lastchange in /var/www/html/cacti/plugins/routerconfigs/functions.php on line 646
2019/02/27 12:13:52 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> exit
2019/02/27 12:13:52 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- exit
2019/02/27 12:13:52 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/02/27 12:13:53 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
2019/02/27 12:13:53 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Checking for valid incoming file at /var/www/html/cacti/SW-OFFICE
2019/02/27 12:13:53 - RCONFIG 10.57.11.16 (Telnet) -> ERROR: Failed to find file at /var/www/html/cacti/SW-OFFICE
2019/02/27 12:13:53 - RCONFIG NOTICE: Failed to download for SW-OFFICE
2019/02/27 12:13:53 - RCONFIG WARNING: 0 Devices Backed Up, 1 Devices Failed, 0 Disabled (ignored) in 7 seconds
2019/02/27 12:13:53 - RCONFIG DEBUG: 0 devices backed up successfully.
2019/02/27 12:13:53 - RCONFIG DEBUG: 1 devices failed to backup.
2019/02/27 12:13:53 - RCONFIG STATS: Time:7.60 Downloaded:0 Failed:1

**Comment by netniV** [comment]
What is your TFTP server's save location?

Also, I noticed a separate issue for `lastchange` being missing which I'll look into.

**Comment by netniV** [comment]
So I have resolved the variable error in #93

**Comment by rtripon** [comment]
My tftp remote path is /home/switches/, but the server is accepting only local paths from what I've tried.
The IP is that of the remote tftp server 'tho.

service tftp
{
	socket_type		= dgram
	protocol		= udp
	wait			= yes
	user			= tftp
	server			= /usr/sbin/in.tftpd
	server_args		= -c -s /home/switches -v
	disable			= no
	per_source		= 11
	cps			= 100 2
	flags			= IPv4
}

**Comment by netniV** [comment]
Right, then you need to give cacti access to that location and ensure that it can remove files as well as read them.

Make sure you have /home/switches set in this location:
![image](https://user-images.githubusercontent.com/9052188/53492520-f6b0e300-3a90-11e9-800b-fa63d064bf37.png)

**Comment by netniV** [comment]
Did that solve your issue @rtripon

**Comment by rtripon** [comment]
Nope, I cant save any path except local folders.
So my tftp server is 192.168.1.1 , all other tftp files are saved on /home/switches on this server.
Now on my new remote cacti server ( 192.168.1.2) on the routerconfig I set 192.168.1.1 for IP...but other than that, is not allowing my to enter /home/switches as path.
2019/03/03 20:16:40 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- SW2960-CX-TESTLACP#
2019/03/03 20:16:40 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Found Prompt (Enabled)
2019/03/03 20:16:40 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: --> exit
2019/03/03 20:16:40 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- exit
2019/03/03 20:16:40 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: <-- 
2019/03/03 20:16:41 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
2019/03/03 20:16:41 - RCONFIG 10.57.11.16 (Telnet) -> DEBUG: Checking for valid incoming file at /var/www/html/cacti/backups/SW-OFFICE  **<-- here is searching for file on local folder wich obviously is missing**
2019/03/03 20:16:41 - RCONFIG 10.57.11.16 (Telnet) -> ERROR: Failed to find file at /var/www/html/cacti/backups/SW-OFFICE
2019/03/03 20:16:41 - RCONFIG NOTICE: Failed to download for SW-OFFICE
2019/03/03 20:16:41 - RCONFIG WARNING: 0 Devices Backed Up, 1 Devices Failed, 0 Disabled (ignored) in 7 seconds

**Comment by netniV** [comment]
Then you need to either NFS mount the folder from .1 or put TFTP onto .2

**Comment by rtripon** [comment]
Ah crap :), I thought I could save files on another TFTP server. So its not a bug, just not possible. Can be close then.
